import 'server-only';import {z} from 'zod';import type {SupabaseClient} from '@supabase/supabase-js';import {AppError} from '../application/models';import {userClient} from './supabase/client';import {researchDAL} from './dal';import type {ProjectReviewData,ProjectCase} from '../domain/project-reactions';
const common={id:z.uuid(),reason:z.string().trim().min(1).max(4000),attested:z.literal(true)};
export const reviewInput=z.discriminatedUnion('action',[z.strictObject({...common,action:z.literal('identity'),version:z.uuid(),label:z.string().trim().min(1).max(200)}),z.strictObject({...common,action:z.literal('mapping'),version:z.uuid(),identity:z.uuid(),revision:z.number().int().nonnegative(),decision:z.enum(['include','exclude']),mapping:z.array(z.strictObject({source:z.uuid(),target:z.uuid()})).min(2).max(8)}),z.strictObject({...common,action:z.literal('source'),anchor:z.uuid(),revision:z.number().int().nonnegative(),decision:z.enum(['attested','withdrawn'])}),z.strictObject({...common,action:z.literal('review'),version:z.uuid(),revision:z.number().int().nonnegative(),decision:z.enum(['accepted','needs_revision','withdrawn'])})]);
function fail(e:{message:string}|null){if(e)throw new AppError(e.message==='KG_FORBIDDEN'?'FORBIDDEN':e.message==='KG_CONFLICT'?'CONFLICT':e.message==='KG_ARCHIVED'?'ARCHIVED':'INVALID');}
export class ProjectReactionDAL{
 constructor(private client:SupabaseClient,private authorize:(project:string)=>Promise<void>){}
 async overview(project:string):Promise<ProjectReviewData>{z.uuid().parse(project);await this.authorize(project);async function all(client:SupabaseClient,table:string,fields:string){const rows:Record<string,unknown>[]=[];for(let offset=0;offset<20000;offset+=1000){const r=await client.from(table).select(fields).eq('project_id',project).order('id').range(offset,offset+999);fail(r.error);rows.push(...((r.data??[]) as unknown as Record<string,unknown>[]));if((r.data?.length??0)<1000)return rows;}throw new AppError('UNAVAILABLE');}
  const [identities,mappings,attestations,reviews,versions,cases,anchors,papers]=await Promise.all([all(this.client,'project_reaction_identities','id,label,seed_version_id,definition,reason'),all(this.client,'reaction_identity_mappings','id,identity_id,case_version_id,revision,decision,mapping,reason,created_by,created_at'),all(this.client,'source_attestations','id,anchor_id,receipt_id,receipt_sha256,passage_hash,revision,decision,reason,created_by,created_at'),all(this.client,'scientific_evidence_reviews','id,case_version_id,revision,decision,source_attestation_id,reason,created_by,created_at'),all(this.client,'research_case_versions','id,case_id,revision,payload,author_kind,review_state,confirmation,change_reason,created_at'),all(this.client,'research_cases','id,paper_id,current_version_id,archived_at'),all(this.client,'source_anchors','id,supersedes_anchor_id,passage_hash'),all(this.client,'papers','id,archived_at')]);
  return {identities,mappings,attestations,reviews,anchors,versions:versions.map(v=>{const c=cases.find(c=>c.id===v.case_id);return {...v,paper_id:c?.paper_id,current:c?.current_version_id===v.id&&!c?.archived_at&&papers.some(p=>p.id===c?.paper_id&&!p.archived_at)} as ProjectCase;})} as ProjectReviewData;
 }
 async write(project:string,raw:unknown){z.uuid().parse(project);await this.authorize(project);const p=reviewInput.parse(raw),args:Record<string,unknown>={p_project:project,p_id:p.id,p_reason:p.reason,p_attested:p.attested};let method:string;
  if(p.action==='identity'){method='create_reaction_identity';Object.assign(args,{p_version:p.version,p_label:p.label});}else if(p.action==='mapping'){method='map_reaction_identity';Object.assign(args,{p_version:p.version,p_identity:p.identity,p_expected:p.revision,p_decision:p.decision,p_mapping:p.mapping});}else if(p.action==='source'){method='attest_source_locator';Object.assign(args,{p_anchor:p.anchor,p_expected:p.revision,p_decision:p.decision});}else{method='review_scientific_evidence';Object.assign(args,{p_version:p.version,p_expected:p.revision,p_decision:p.decision});}const r=await this.client.rpc(method,args);fail(r.error);return r.data as string;
 }
}
export async function projectReactionDAL(){return new ProjectReactionDAL(await userClient(),async p=>{await (await researchDAL()).project(p);});}
