import 'server-only';
import {z} from 'zod';
import type {SupabaseClient} from '@supabase/supabase-js';
import {caseSchema,parseCaseImport,caseDiff,type ResearchCase,type CaseVersion} from '../domain/research-case';
import {researchDAL} from './dal';
import {userClient} from './supabase/client';
import {AppError,uuid} from '../application/models';
export type CaseRecord={id:string;paper_id:string;revision:number;current_version_id:string;archived_at:string|null};
export type ImportPreview={id:string;diff:ReturnType<typeof caseDiff>;humanProtected:boolean;stale:boolean;caseId:string;status:string};
function fail(error:{message:string}|null){if(error)throw new AppError(error.message==='KG_FORBIDDEN'?'FORBIDDEN':error.message==='KG_CONFLICT'?'CONFLICT':error.message==='KG_ARCHIVED'?'ARCHIVED':'INVALID');}
export class CaseDAL{
 constructor(private client:SupabaseClient,private authorize:(project:string,paper:string)=>Promise<void>){}
 private async scope(project:string,paper:string){uuid.parse(project);uuid.parse(paper);await this.authorize(project,paper);}
 async list(project:string,paper:string){await this.scope(project,paper);const {data,error}=await this.client.from('research_cases').select('id,paper_id,revision,current_version_id,archived_at').eq('project_id',project).eq('paper_id',paper);fail(error);return data as CaseRecord[];}
 async detail(project:string,paper:string,id:string){await this.scope(project,paper);uuid.parse(id);const {data,error}=await this.client.from('research_cases').select('id,paper_id,revision,current_version_id,archived_at').eq('project_id',project).eq('paper_id',paper).eq('id',id).maybeSingle();fail(error);if(!data)return null;const versions=await this.client.from('research_case_versions').select('id,case_id,revision,payload,author_kind,review_state,confirmation,change_reason,created_at').eq('project_id',project).eq('case_id',id).order('revision',{ascending:false});fail(versions.error);return {record:data as CaseRecord,versions:versions.data as CaseVersion[]};}
 async save(project:string,paper:string,id:string,revision:number,payload:unknown,reason:string){await this.scope(project,paper);uuid.parse(id);z.number().int().nonnegative().parse(revision);z.string().trim().min(1).max(4000).parse(reason);const parsed=caseSchema.parse(payload);const {data,error}=await this.client.rpc('save_research_case',{p_project:project,p_paper:paper,p_case:id,p_expected:revision,p_payload:parsed,p_reason:reason});fail(error);return data as string;}
 async review(project:string,paper:string,id:string,revision:number,reason:string){const detail=await this.detail(project,paper,id);if(!detail)throw new AppError('FORBIDDEN');z.number().int().nonnegative().parse(revision);z.string().trim().min(1).max(4000).parse(reason);const {data,error}=await this.client.rpc('review_research_case',{p_project:project,p_case:id,p_expected:revision,p_reason:reason});fail(error);return data as string;}
 async archive(project:string,paper:string,id:string,revision:number,archived:boolean){if(!await this.detail(project,paper,id))throw new AppError('FORBIDDEN');z.number().int().nonnegative().parse(revision);const {error}=await this.client.rpc('archive_research_case',{p_project:project,p_case:id,p_expected:revision,p_archived:archived});fail(error);}
 async stage(project:string,paper:string,requestId:string,raw:string):Promise<ImportPreview>{await this.scope(project,paper);uuid.parse(requestId);const parsed=parseCaseImport(raw);if(parsed.project_id!==project||parsed.paper_id!==paper)throw new AppError('INVALID');const detail=await this.detail(project,paper,parsed.case_id);const {data,error}=await this.client.rpc('stage_research_import',{p_project:project,p_request:requestId,p_content:raw});fail(error);const current=detail?.versions.find(v=>v.id===detail.record.current_version_id);return {id:data as string,caseId:parsed.case_id,diff:caseDiff(current?.payload??null,parsed.payload),humanProtected:current?.author_kind==='human'||!!current?.review_state.startsWith('human_'),stale:parsed.expected_revision!==(detail?.record.revision??0),status:'staged'};}
 async apply(project:string,paper:string,batchId:string){await this.scope(project,paper);uuid.parse(batchId);const b=await this.client.from('case_import_batches').select('proposal').eq('project_id',project).eq('id',batchId).maybeSingle();fail(b.error);if(!b.data||b.data.proposal.paper_id!==paper)throw new AppError('FORBIDDEN');const {data,error}=await this.client.rpc('apply_research_import',{p_project:project,p_batch:batchId});fail(error);return {versionId:data as string,caseId:b.data.proposal.case_id as string};}
}
export async function caseDAL(){return new CaseDAL(await userClient(),async(project,paper)=>{await (await researchDAL()).paper(project,paper);});}
export type {ResearchCase};
