import 'server-only';
import {z} from 'zod';import type {SupabaseClient} from '@supabase/supabase-js';
import {AppError} from '../application/models';import {userClient} from './supabase/client';import {researchDAL} from './dal';
export const anchorInput=z.strictObject({id:z.uuid(),document:z.uuid(),start:z.number().int().min(1).max(1000000),end:z.number().int().min(1).max(1000000),label:z.string().max(200),passage:z.string().min(1).max(16000),section:z.string().max(500),locator:z.string().max(500),supersedes:z.uuid().nullable()}).refine(p=>p.end>=p.start&&p.passage.trim().length>0);
export type SourceDocument={id:string;edition_label:string;receipt:{id:string;intent_id:string;sha256:string;content_revision:string;byte_size:number}};
export type SourceAnchor={id:string;paper_document_id:string;physical_page_start:number;physical_page_end:number;printed_page_label:string|null;verbatim_passage:string;passage_hash:string;section:string|null;figure_table_scheme:string|null;anchor_verified_at:string|null;supersedes_anchor_id:string|null};
export class SourceDAL{
 constructor(private client:SupabaseClient,private authorize:(project:string,paper:string)=>Promise<void>){}
 async list(project:string,paper:string){z.uuid().parse(project);z.uuid().parse(paper);await this.authorize(project,paper);const docs=await this.client.from('paper_documents').select('id,edition_label,document_receipt_id').eq('project_id',project).eq('paper_id',paper);if(docs.error)throw new AppError('UNAVAILABLE');const receipts=await this.client.from('document_receipts').select('id,intent_id,sha256,content_revision,byte_size').eq('project_id',project).eq('paper_id',paper).eq('state','stored_unparsed');if(receipts.error)throw new AppError('UNAVAILABLE');const documents:SourceDocument[]=(docs.data??[]).flatMap(d=>{const r=receipts.data?.find(r=>r.id===d.document_receipt_id);return r?[{id:d.id,edition_label:d.edition_label,receipt:{...r,byte_size:Number(r.byte_size)}}]:[];});if(!documents.length)return {documents,anchors:[] as SourceAnchor[]};const anchors=await this.client.from('source_anchors').select('id,paper_document_id,physical_page_start,physical_page_end,printed_page_label,verbatim_passage,passage_hash,section,figure_table_scheme,anchor_verified_at,supersedes_anchor_id').eq('project_id',project).in('paper_document_id',documents.map(d=>d.id)).order('created_at',{ascending:false});if(anchors.error)throw new AppError('UNAVAILABLE');return {documents,anchors:anchors.data as SourceAnchor[]};}
 async create(project:string,paper:string,raw:unknown){z.uuid().parse(project);z.uuid().parse(paper);await this.authorize(project,paper);const p=anchorInput.parse(raw);const {data,error}=await this.client.rpc('create_draft_source_anchor',{p_project:project,p_paper:paper,p_id:p.id,p_document:p.document,p_start:p.start,p_end:p.end,p_label:p.label,p_passage:p.passage,p_section:p.section,p_locator:p.locator,p_supersedes:p.supersedes});if(error)throw new AppError(error.message==='KG_CONFLICT'?'CONFLICT':error.message==='KG_FORBIDDEN'?'FORBIDDEN':'INVALID');return data as string;}
}
export async function sourceDAL(){return new SourceDAL(await userClient(),async(p,d)=>{await (await researchDAL()).paper(p,d);});}
