import {test,expect} from '@playwright/test';
test('PDF UI labels, pending, retry, cancel and no double tap on mobile',async({page})=>{
 let uploads=0,begins=0;
 await page.route('**/api/pdf?**',async route=>{const action=new URL(route.request().url()).searchParams.get('action');if(action==='begin'){begins++;await route.fulfill({json:{id:'22222222-2222-4222-8222-222222222222'}});}else if(action==='upload'){uploads++;await new Promise(r=>setTimeout(r,250));await route.fulfill({status:503,json:{error:'DATABASE'}});}else await route.fulfill({json:{cancelled:true}});});
 await page.goto('http://127.0.0.1:3191');
 await page.getByLabel('PDF ファイル').setInputFiles({name:'synthetic.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7 SYNTHETIC UI ONLY')});
 await page.getByLabel('取得元 URL または出典').fill('SYNTHETIC fixture');await page.getByLabel('アクセスの根拠').fill('generated test');
 await page.getByRole('button',{name:'PDF をアップロード',exact:true}).click();await expect(page.getByRole('button',{name:'アップロード・検証中…'})).toBeDisabled();await expect(page.getByLabel('アップロード進捗')).toBeVisible();
 await expect(page.getByRole('status').filter({hasText:'DATABASE'})).toBeVisible();expect(uploads).toBe(1);await expect(page.getByLabel('取得元 URL または出典')).toHaveValue('SYNTHETIC fixture');
 await page.getByRole('button',{name:'同じ試行を再送'}).click();await expect(page.getByRole('status').filter({hasText:'DATABASE'})).toBeVisible();expect(begins).toBe(1);expect(uploads).toBe(2);
 await page.getByRole('button',{name:'キャンセル / 新しい試行'}).click();await expect(page.getByRole('status').filter({hasText:'試行をキャンセルしました'})).toBeVisible();await expect(page.getByLabel('PDF ファイル')).toBeEnabled();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`/tmp/kg-task3-${test.info().project.name}-pdf.png`,fullPage:true});
});
test('production PDF upload endpoint fails closed without verifier',async({request})=>{const result=await request.post('/api/pdf?action=begin',{data:{}});expect(result.status()).toBe(503);expect(await result.json()).toEqual({error:'UNCONFIGURED'});expect(result.headers()['cache-control']).toContain('no-store');});
test('successful finalize permits a new edition without cancelling immutable finalized attempt',async({page})=>{let cancels=0;await page.route('**/api/pdf?**',async route=>{const action=new URL(route.request().url()).searchParams.get('action');if(action==='cancel')cancels++;await route.fulfill({json:action==='begin'?{id:'22222222-2222-4222-8222-222222222222'}:{matchedKnownBytes:false}});});await page.goto('http://127.0.0.1:3191');await page.getByLabel('PDF ファイル').setInputFiles({name:'synthetic.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7 SYNTHETIC UI ONLY')});await page.getByLabel('取得元 URL または出典').fill('synthetic');await page.getByLabel('アクセスの根拠').fill('test');await page.getByRole('button',{name:'PDF をアップロード',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'新しい PDF 版を保存'})).toBeVisible();await page.getByRole('button',{name:'別版の PDF を追加'}).click();expect(cancels).toBe(0);await expect(page.getByLabel('PDF ファイル')).toBeEnabled();await expect(page.getByRole('button',{name:'PDF をアップロード',exact:true})).toBeEnabled();});
