import {chemicalIdentity} from './chemical-fields';
import {classifyGraph,type Filter} from './graph';import type {CaseVersion} from './research-case';import type {Evidence} from './contracts';
export type ReactionIdentity={id:string;label:string;seed_version_id:string;definition:CaseVersion['payload'];reason:string;created_by?:string;created_at?:string};
export type ReactionMapping={id:string;identity_id:string;case_version_id:string;revision:number;decision:'include'|'exclude';mapping:{source:string;target:string}[];reason:string;created_by?:string;created_at?:string};
export type SourceAttestation={id:string;anchor_id:string;receipt_id:string;receipt_sha256:string;passage_hash:string;revision:number;decision:'attested'|'withdrawn';reason:string;created_by:string;created_at?:string};
export type EvidenceReview={id:string;case_version_id:string;revision:number;decision:'accepted'|'needs_revision'|'withdrawn';source_attestation_id:string|null;reason:string;created_by:string;created_at?:string};
export type ProjectCase=CaseVersion&{paper_id:string;current:boolean};
export type CompoundLink={id:string;source_identity:string;source_compound:string;target_identity:string;target_compound:string;revision:number;decision:'include'|'exclude';reason:string;created_by?:string;created_at?:string};
export type ProjectReviewData={compoundLinks?:CompoundLink[];identities:ReactionIdentity[];mappings:ReactionMapping[];attestations:SourceAttestation[];reviews:EvidenceReview[];versions:ProjectCase[];anchors:{physical_page_start?:number;physical_page_end?:number;printed_page_label?:string|null;verbatim_passage?:string;id:string;supersedes_anchor_id:string|null;passage_hash:string}[]};
function latest<T extends {revision:number}>(rows:T[]){return rows.reduce<T|null>((best,r)=>!best||r.revision>best.revision?r:best,null);}
export function validReactionMapping(definition:CaseVersion['payload'],payload:CaseVersion['payload'],mapping:ReactionMapping['mapping']){
 if(definition.claim.scope!==payload.claim.scope||definition.reaction.representation_scope!==payload.reaction.representation_scope||mapping.length!==definition.compounds.length||mapping.length!==payload.compounds.length||new Set(mapping.map(m=>m.source)).size!==mapping.length||new Set(mapping.map(m=>m.target)).size!==mapping.length)return false;
 const keys=['node_type','structure_context','stereochemistry','protonation','formula','charge'] as const;
 if(mapping.some(m=>{const a=payload.compounds.find(c=>c.id===m.source),b=definition.compounds.find(c=>c.id===m.target);return !a||!b||keys.some(k=>a[k]!==b[k])||JSON.stringify(chemicalIdentity(a.structure))!==JSON.stringify(chemicalIdentity(b.structure));}))return false;
 const parts=(p:CaseVersion['payload'],mapped:boolean)=>p.reaction.participants.map(x=>JSON.stringify([mapped?mapping.find(m=>m.source===x.compound_id)?.target:x.compound_id,x.role,x.coefficient])).sort();
 return JSON.stringify(parts(definition,false))===JSON.stringify(parts(payload,true));
}
export function aggregateIdentity(identity:ReactionIdentity,data:ProjectReviewData,filters:Filter[],stage:'reaction'|'pretreatment'|'workup'|'analysis'='reaction'){
 const evidence:Evidence[]=[],bundles:Parameters<typeof classifyGraph>[0]['bundles']=[],rows:{version:ProjectCase;reason:string;eligible:boolean}[]=[];
 for(const v of data.versions){const mapping=latest(data.mappings.filter(m=>m.case_version_id===v.id));if(!mapping||mapping.identity_id!==identity.id)continue;const p=v.payload,review=latest(data.reviews.filter(r=>r.case_version_id===v.id)),anchor=data.anchors.find(a=>a.id===p.evidence.source_anchor_id),attestation=latest(data.attestations.filter(a=>a.anchor_id===anchor?.id));let reason='';
  if(!v.current)reason='旧改訂・アーカイブ';else if(mapping.decision!=='include')reason='対応付けを除外';else if(!validReactionMapping(identity.definition,p,mapping.mapping))reason='参加物・係数・構造・範囲の対応が不一致';else if(p.claim.scope!==identity.definition.claim.scope||p.reaction.representation_scope!==identity.definition.reaction.representation_scope)reason='主張・機構の範囲が不一致';else if(review?.decision!=='accepted')reason='科学的レビュー待ち・差戻し・撤回';else if(!anchor||data.anchors.some(a=>a.supersedes_anchor_id===anchor.id))reason='出典未接続・訂正あり';else if(attestation?.decision!=='attested'||attestation.id!==review.source_attestation_id||attestation.passage_hash!==anchor.passage_hash)reason='現在の人による出典照合が必要';else if(p.evidence.source_access!=='fulltext')reason='本文へのアクセス未確認';else if(['directly_observed','strongly_supported'].includes(p.evidence.evidence_type)&&(p.experiment.origin_resolution_status!=='confirmed'||!p.experiment.original_experiment_id||!p.experiment.independence_group_id))reason='元実験・独立性が未解決';else if(['directly_observed','strongly_supported'].includes(p.evidence.evidence_type)&&p.evidence.measured_scope!==null&&p.evidence.measured_scope!==p.claim.scope)reason='観測範囲を越える主張';
  rows.push({version:v,reason:reason||'レビュー済み（条件を個別照合）',eligible:!reason});if(reason)continue;const bundleId=v.id+':conditions';bundles.push({id:bundleId,experiment_version_id:v.id+':experiment',stage:p.experiment.stage,basis:'experiment',values:p.experiment.conditions});evidence.push({id:v.id,claim_id:identity.id,reporting_paper_id:v.paper_id,condition_bundle_id:bundleId,original_experiment_id:p.experiment.original_experiment_id,independence_group_id:p.experiment.independence_group_id,origin_resolution_status:p.experiment.origin_resolution_status,stance:p.evidence.stance,evidence_type:p.evidence.evidence_type,strength_assessment:'unassessed',current_assertion_status:'active',measured_scope:p.evidence.measured_scope,strength_rationale:p.evidence.strength_rationale,review_state:'human_reviewed',epistemic_origin:p.evidence.epistemic_origin,source_access:p.evidence.source_access,extraction_confidence:null,source_anchor_ids:[anchor!.id],dependency_ids:[],alternatives_tested:p.evidence.alternatives_tested,limitations:p.evidence.limitations});
 }
 const p=identity.definition;return {rows,projection:classifyGraph({reaction:{...p.reaction,id:identity.id,participants:p.reaction.participants.map(x=>({compound_version_id:x.compound_id,role:x.role,coefficient:x.coefficient,primary_for_display:x.primary_for_display}))},claim:{id:identity.id,reaction_version_id:identity.id,scope:p.claim.scope,proposition:p.claim.proposition},evidence,bundles,filters,stage,reviewedOnly:true,includeUnknown:true,showRefutations:true})};
}
