import {z} from 'zod';
import {conditionSchema,conditionIssue,scope} from './contracts';
import {classifyGraph,type Filter} from './graph';
const uuid=z.uuid(),short=z.string().min(1).max(200).regex(/\S/),text=z.string().min(1).max(4000).regex(/\S/);
export const caseCompound=z.strictObject({id:uuid,name:short,aliases:z.array(short).max(8),node_type:z.enum(['discrete_molecule','intermediate','polymer','polymer_site','mixture','class']),structure_context:z.enum(['free','bound','polymer_site','unknown']),stereochemistry:z.string().max(500).nullable(),protonation:z.string().max(500).nullable(),formula:z.string().max(200).nullable(),charge:z.number().int().min(-100).max(100).nullable(),epistemic_status:z.enum(['observed','hypothetical','unspecified'])});
export const caseSchema=z.strictObject({
 compounds:z.array(caseCompound).min(2).max(8),
 reaction:z.strictObject({id:uuid,representation_scope:z.enum(['net_conversion','elementary_step','pathway_segment']),equation_balance_status:z.enum(['checked','unchecked','not_applicable','unknown']),product_inventory_status:z.enum(['complete','partial','unknown']),participants:z.array(z.strictObject({compound_id:uuid,role:z.enum(['reactant','product','formal_auxiliary']),coefficient:z.number().positive().max(1000000).nullable(),primary_for_display:z.boolean()})).min(2).max(16)}),
 claim:z.strictObject({scope,proposition:text,asserted_by:z.enum(['authors','analyst'])}),
 experiment:z.strictObject({id:uuid,original_experiment_id:short.nullable(),independence_group_id:short.nullable(),origin_resolution_status:z.enum(['confirmed','unresolved']),stage:z.enum(['reaction','pretreatment','workup','analysis']),conditions:z.array(conditionSchema).max(20)}),
 evidence:z.strictObject({id:uuid,stance:z.enum(['supports','refutes','inconclusive']),evidence_type:z.enum(['directly_observed','strongly_supported','proposed','adopted_from_prior_literature','speculative']),measured_scope:scope.nullable(),epistemic_origin:z.enum(['experiment_report','authors_interpretation','cited_interpretation','analyst_inference']),source_access:z.enum(['fulltext','abstract_only','secondary_only','unavailable']),strength_rationale:text,alternatives_tested:z.array(short).max(20),limitations:z.array(short).max(20),source_anchor_id:uuid.nullable()})
}).superRefine((p,ctx)=>{
 const issue=(message:string)=>ctx.addIssue({code:'custom',message});const ids=[...p.compounds.map(c=>c.id),p.reaction.id,p.experiment.id,p.evidence.id];if(new Set(ids).size!==ids.length)issue('IDs must be distinct; names never merge identities');
 if(!p.reaction.participants.some(x=>x.role==='reactant')||!p.reaction.participants.some(x=>x.role==='product'))issue('Reaction needs reactant and product');
 if(p.reaction.participants.some(x=>!p.compounds.some(c=>c.id===x.compound_id)))issue('Unresolved participant');
 if(p.claim.scope==='elementary_mechanism'&&p.reaction.representation_scope!=='elementary_step')issue('Net conversion cannot stand for elementary mechanism');
 if(p.evidence.evidence_type==='directly_observed'&&p.evidence.measured_scope!==p.claim.scope)issue('Observation scope mismatch');
 if(p.evidence.evidence_type==='strongly_supported'&&(!p.evidence.alternatives_tested.length||!p.evidence.limitations.length))issue('Strong support needs alternatives and limitations');
 if(p.experiment.origin_resolution_status==='confirmed'&&(!p.experiment.original_experiment_id||!p.experiment.independence_group_id))issue('Confirmed experiment needs original identity and group');
 if(p.evidence.evidence_type==='adopted_from_prior_literature'&&p.experiment.origin_resolution_status==='confirmed')issue('Cross-case adopted origin resolution is outside this profile');
 for(const c of p.experiment.conditions){const problem=conditionIssue(c);if(problem)issue(problem);}
});
export type ResearchCase=z.infer<typeof caseSchema>;
export const caseImportSchema=z.strictObject({schema_version:z.literal('research-case/0.1'),project_id:uuid,paper_id:uuid,case_id:uuid,expected_revision:z.number().int().nonnegative(),analysis_run:z.strictObject({id:short,adapter:z.literal('dot_manual_json'),protocol_version:short}),payload:caseSchema});
export type CaseImport=z.infer<typeof caseImportSchema>;
export type CaseVersion={id:string;case_id:string;revision:number;payload:ResearchCase;author_kind:'human'|'ai';review_state:'unreviewed'|'ai_generated'|'human_reviewed'|'human_corrected';confirmation:'draft'|'confirmed';change_reason:string;created_at:string};
export function parseCaseImport(raw:string){if(new TextEncoder().encode(raw).length>131072)throw Error('Import exceeds 128 KiB');return caseImportSchema.parse(JSON.parse(raw));}
export function caseDiff(before:ResearchCase|null,after:ResearchCase){return (['compounds','reaction','claim','experiment','evidence'] as const).filter(k=>JSON.stringify(before?.[k])!==JSON.stringify(after[k])).map(section=>({section,before:before?.[section]??null,after:after[section]}));}
export function projectCase(v:CaseVersion,sourceValid:boolean,filters:Filter[]=[]){
 if(v.confirmation!=='confirmed'||!sourceValid||!v.payload.evidence.source_anchor_id||v.payload.evidence.source_access!=='fulltext'||v.payload.experiment.origin_resolution_status!=='confirmed'||!v.payload.experiment.original_experiment_id||!v.payload.experiment.independence_group_id||!['human_reviewed','human_corrected'].includes(v.review_state))return {line_style:'hidden',reason:'Draft or source not verified; no inferred proposal'};
 const p=v.payload,bundleId=`${v.id}:conditions`,claimId=`${v.id}:claim`;
 return classifyGraph({reaction:{...p.reaction,id:v.id,participants:p.reaction.participants.map(x=>({compound_version_id:`${v.id}:${x.compound_id}`,role:x.role,coefficient:x.coefficient,primary_for_display:x.primary_for_display}))},claim:{id:claimId,reaction_version_id:v.id,scope:p.claim.scope,proposition:p.claim.proposition},bundles:[{id:bundleId,experiment_version_id:`${v.id}:experiment`,stage:p.experiment.stage,basis:'experiment',values:p.experiment.conditions}],evidence:[{id:p.evidence.id,claim_id:claimId,reporting_paper_id:'bound-in-database',condition_bundle_id:bundleId,original_experiment_id:p.experiment.original_experiment_id,independence_group_id:p.experiment.independence_group_id,origin_resolution_status:p.experiment.origin_resolution_status,stance:p.evidence.stance,evidence_type:p.evidence.evidence_type,strength_assessment:'unassessed',current_assertion_status:'active',measured_scope:p.evidence.measured_scope,strength_rationale:p.evidence.strength_rationale,review_state:v.review_state as 'human_reviewed'|'human_corrected',epistemic_origin:p.evidence.epistemic_origin,source_access:p.evidence.source_access,extraction_confidence:null,source_anchor_ids:p.evidence.source_anchor_id?[p.evidence.source_anchor_id]:[],dependency_ids:[],alternatives_tested:p.evidence.alternatives_tested,limitations:p.evidence.limitations}],filters,reviewedOnly:true});
}
export function emptyResearchCase(makeId:()=>string):ResearchCase{const a=makeId(),b=makeId();return {compounds:[a,b].map(id=>({id,name:'',aliases:[],node_type:'discrete_molecule',structure_context:'unknown',stereochemistry:null,protonation:null,formula:null,charge:null,epistemic_status:'unspecified'})),reaction:{id:makeId(),representation_scope:'net_conversion',equation_balance_status:'unknown',product_inventory_status:'unknown',participants:[{compound_id:a,role:'reactant',coefficient:null,primary_for_display:true},{compound_id:b,role:'product',coefficient:null,primary_for_display:true}]},claim:{scope:'net_conversion',proposition:'',asserted_by:'analyst'},experiment:{id:makeId(),original_experiment_id:null,independence_group_id:null,origin_resolution_status:'unresolved',stage:'reaction',conditions:[]},evidence:{id:makeId(),stance:'inconclusive',evidence_type:'speculative',measured_scope:null,epistemic_origin:'analyst_inference',source_access:'unavailable',strength_rationale:'',alternatives_tested:[],limitations:[],source_anchor_id:null}};}
