import {z} from 'zod';
import {caseImportSchema} from './research-case';
export const questionStatuses=['open','searching','waiting_for_pdf','analyzing','answered','unresolved','rejected','low_priority'] as const;
export const questionRevisionSchema=z.strictObject({question:z.string().trim().min(1).max(2000),importance:z.string().max(4000),priority:z.number().int().min(1).max(4),status:z.enum(questionStatuses),conclusion:z.string().max(8000),review_state:z.enum(['unreviewed','human_reviewed','human_corrected']),result_id:z.uuid().nullable(),evidence_versions:z.array(z.uuid()).max(20),reason:z.string().trim().min(1).max(2000)}).superRefine((p,c)=>{if(p.status==='answered'&&(!p.conclusion.trim()||p.review_state==='unreviewed'||!p.evidence_versions.length))c.addIssue({code:'custom',message:'Answered requires a human-reviewed conclusion and evidence versions'});if(new Set(p.evidence_versions).size!==p.evidence_versions.length)c.addIssue({code:'custom',message:'Duplicate evidence references'});});
export type QuestionRevision=z.infer<typeof questionRevisionSchema>;
export type QuestionState={id:string;question:string;revision:number;data:QuestionRevision|null};
export const researchResultSchema=z.strictObject({schema_version:z.literal('research-result/0.1'),request_id:z.uuid(),request_hash:z.string().regex(/^[0-9a-f]{64}$/),case_import:caseImportSchema,conclusion:z.string().trim().min(1).max(8000),uncertainties:z.array(z.string().trim().min(1).max(2000)).max(20)});
export type ResearchResult=z.infer<typeof researchResultSchema>;
export function parseResearchResult(raw:string){if(new TextEncoder().encode(raw).length>196608)throw Error('Result exceeds 192 KiB');return researchResultSchema.parse(JSON.parse(raw));}
export const handoffInstructions='Analyze only this paper for this question and case. No recursive exploration. Return research-result/0.1 using the supplied request ID/hash and research-case/0.1 template. Preserve claim scope, experiment identity, conditions/units/unknowns, contradictions and authors versus analyst attribution. Do not invent source anchors or verified passages. Use existing anchor IDs only when the passage actually supports the claim; otherwise null. Return unresolved uncertainty instead of upgrading observations to a mechanism. The conclusion is an unreviewed proposal. Never change expected_revision to bypass conflicts. Do not include credentials or PDF bytes.';
