import {conditionIssue} from './contracts';
import {aggregateIdentity,type ProjectReviewData,type ProjectCase} from './project-reactions';
import type {Filter} from './graph';
export type BoardOptions={substrate:string;alkali:string;aqueous:string;concentrationMin:string;concentrationMax:string;concentrationUnit:string;concentrationBasis:string;temperatureMin:string;temperatureMax:string;stage:'reaction'|'pretreatment'|'workup'|'analysis';atmosphere:string;catalyst:string;evidenceClass:string;review:string};
export const boardDefaults:BoardOptions={substrate:'',alkali:'',aqueous:'',concentrationMin:'',concentrationMax:'',concentrationUnit:'mol/L',concentrationBasis:'solution_volume',temperatureMin:'',temperatureMax:'',stage:'reaction',atmosphere:'',catalyst:'',evidenceClass:'',review:'accepted'};
export function boardFilters(o:BoardOptions):Filter[]{const out:Filter[]=[];const term=(key:string,dimension:string,basis:string,value:string,only=false)=>{if(value)out.push({key,dimension,basis,unit:'',terms:[value],only});};term('substrate','composition','feed',o.substrate);term('alkali','composition','added_alkali',o.alkali,true);term('solvent','composition','reaction_medium',o.aqueous,o.aqueous==='non_aqueous');term('added_catalyst','composition','added_catalyst',o.catalyst,true);
 const interval=(key:string,dimension:string,basis:string,unit:string,min:string,max:string)=>{if(min!==''||max!=='')out.push({key,dimension,basis,unit,...(min!==''?{min:Number(min)}:{}),...(max!==''?{max:Number(max)}:{})});};interval('temperature','temperature','reaction_medium','degC',o.temperatureMin,o.temperatureMax);interval('NaOH_concentration','concentration',o.concentrationBasis,o.concentrationUnit,o.concentrationMin,o.concentrationMax);return out;}
export function invalidBoardRange(o:BoardOptions){return [[o.temperatureMin,o.temperatureMax],[o.concentrationMin,o.concentrationMax]].some(([a,b])=>(a!==''&&!Number.isFinite(Number(a)))||(b!==''&&!Number.isFinite(Number(b)))||(a!==''&&b!==''&&Number(a)>Number(b)))||[o.concentrationMin,o.concentrationMax].some(x=>x!==''&&Number(x)<0);}
export function oxygenGroup(v:ProjectCase,stage:BoardOptions['stage']):'oxygen'|'oxygen_free'|'unknown'{const cs=v.payload.experiment.conditions.filter(c=>c.key==='atmosphere');if(v.payload.experiment.stage!==stage||cs.length!==1)return 'unknown';const c=cs[0];if(conditionIssue(c)||c.value_state!=='reported'||c.dimension!=='composition'||c.basis!=='headspace'||c.unit!==''||c.kind==='interval')return 'unknown';if(c.terms.some(t=>['oxygen','air'].includes(t))){if(c.terms.includes('oxygen_free'))return 'unknown';return 'oxygen';}if(c.inventory_complete&&c.terms.length&&c.terms.every(t=>['inert','oxygen_free'].includes(t)))return 'oxygen_free';return 'unknown';}
export function boardRows(data:ProjectReviewData,o:BoardOptions){if(invalidBoardRange(o))return [];const filters=boardFilters(o);return data.identities.flatMap(identity=>['oxygen','oxygen_free','unknown'].filter(g=>!o.atmosphere||o.atmosphere===g).flatMap(group=>{const versions=data.versions.filter(v=>{if(oxygenGroup(v,o.stage)!==group||o.evidenceClass&&v.payload.evidence.evidence_type!==o.evidenceClass)return false;const accepted=data.reviews.filter(r=>r.case_version_id===v.id).sort((a,b)=>b.revision-a.revision)[0]?.decision==='accepted';return o.review==='all'||(o.review==='pending'?!accepted:accepted);});const result=aggregateIdentity(identity,{...data,versions},filters,o.stage);return result.rows.length?[{key:identity.id+':'+group,identity,group,...result}]:[];}));}
export type BoardRow=ReturnType<typeof boardRows>[number];
