import test from 'node:test';import assert from 'node:assert/strict';
import initRDKit from '@rdkit/rdkit';
import {caseSchema,caseImportSchema} from '../src/domain/research-case';
import {emptyChemicalStructure,emptyReactionDescription,chemicalStructure,depictionInput,chemicalIdentity} from '../src/domain/chemical-fields';
import {syntheticCase} from './fixtures/research-case';
import {validReactionMapping} from '../src/domain/project-reactions';
test('legacy cases roundtrip unchanged; missing fields do not imply irreversible or absent structure',()=>{const p=syntheticCase();assert.deepEqual(caseSchema.parse(p),p);assert.equal(p.reaction.description,undefined);const copy=structuredClone(p);copy.compounds[0].structure={...emptyChemicalStructure(),smiles:'N[C@@H](C)C(=O)[O-]',inchi:'InChI=1S/CH4/h1H4',cas:'50-99-7'};copy.reaction.description={...emptyReactionDescription(),reaction_type:'SYNTHETIC net conversion',description:'SYNTHETIC <script>alert(1)</script>',reversibility:'unknown',attribution:'analyst'};assert.deepEqual(caseSchema.parse(copy),copy);assert.notDeepEqual(chemicalIdentity(copy.compounds[0].structure),chemicalIdentity(undefined));const mapping=p.compounds.map(c=>({source:c.id,target:c.id}));assert.equal(validReactionMapping(p,copy,mapping),false);const envelope={schema_version:'research-case/0.1',project_id:p.reaction.id,paper_id:p.reaction.id,case_id:p.reaction.id,expected_revision:0,analysis_run:{id:'synthetic',adapter:'dot_manual_json',protocol_version:'0.1'},payload:copy};assert.ok(caseImportSchema.safeParse(envelope).success);});
test('identifier bounds, CAS checksum and markup input remain explicit',()=>{assert.ok(chemicalStructure.safeParse({...emptyChemicalStructure(),cas:'50-99-7'}).success);assert.equal(chemicalStructure.safeParse({...emptyChemicalStructure(),cas:'50-99-8'}).success,false);assert.equal(depictionInput('<svg onload=alert(1)>'),'unsupported');assert.equal(depictionInput('C'.repeat(1025)),'too_large');assert.equal(depictionInput(null),'missing');assert.equal(depictionInput('C[NH2+]C'),'ready');assert.equal(depictionInput('N[C@@H](C)C(=O)[O-]'),'ready');});
test('pinned RDKit sanitizes invalid valence and depicts stereo/charge deterministically',async()=>{const rdkit=await initRDKit({print:()=>{},printErr:()=>{}});for(const s of ['C1CC','C(C)(C)(C)(C)C']){const m=rdkit.get_mol(s);assert.ok(!m||!m.is_valid());m?.delete();}const strings=['N[C@@H](C)C(=O)[O-]','N[C@H](C)C(=O)[O-]','N[C@@H](C)C(=O)O'];const drawings=strings.map(s=>{const m=rdkit.get_mol(s)!;assert.equal(m.is_valid(),true);m.set_new_coords(false);const a=m.get_svg(300,210);m.set_new_coords(false);assert.equal(m.get_svg(300,210),a);assert.match(m.get_smiles(),/@/);if(s.includes('[O-]'))assert.match(m.get_smiles(),/\[O-\]/);m.delete();return a;});assert.notEqual(drawings[0],drawings[1]);assert.notEqual(drawings[0],drawings[2]);const polymer=rdkit.get_mol('C'.repeat(129))!;assert.equal(polymer.get_num_atoms(),129);polymer.delete();});

import {networkFixture} from './fixtures/network';
import {boardRows,boardDefaults} from '../src/domain/whiteboard';
import {reactionNetwork} from '../src/domain/reaction-network';
test('structure thumbnails do not overlap vertically in the reaction network',()=>{const d=networkFixture();for(const i of d.identities)for(const c of i.definition.compounds)c.structure={...emptyChemicalStructure(),smiles:'CCO'};for(const v of d.versions)for(const c of v.payload.compounds)c.structure={...emptyChemicalStructure(),smiles:'CCO'};const n=reactionNetwork(boardRows(d,boardDefaults));for(const a of n.nodes.filter(n=>n.kind==='compound'))for(const b of n.nodes.filter(n=>n.kind==='compound'&&n.id!==a.id&&n.lane===a.lane&&n.x===a.x))assert.ok(a.y+a.height<=b.y||b.y+b.height<=a.y);});
