import 'server-only';
import {createHash,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {DriveError,DRIVE_SCOPE,type DriveBinding} from '../../application/drive';
import {authorizationRequest} from './oauth';
import {sessionURL} from '../../application/drive-upload';
import type {SecretVault} from './vault';
import type {TokenProvider} from './adapter';
import type {SessionVault} from './service';
const tokenSchema=z.object({accessToken:z.string().min(1),refreshToken:z.string().min(1),expiresAt:z.number(),accountId:z.string().min(1)});
const stateSchema=z.object({project:z.uuid(),binding:z.uuid(),expectedAccount:z.string().nullable(),folder:z.string().nullable(),verifier:z.string().min(1)});
export interface OAuthScope {project(id:string):Promise<DriveBinding|null>;bind(id:string,project:string,account:string,folder:string):Promise<void>;}
export type GoogleOAuthConfig={clientId:string;clientSecret:string;redirectUri:string};
export class DriveOAuth implements TokenProvider {
 constructor(private config:GoogleOAuthConfig,private userId:string,private vault:SecretVault,private scope:OAuthScope,private http:typeof fetch=fetch){const u=new URL(config.redirectUri);if(!config.clientId||!config.clientSecret||u.protocol!=='https:'||u.search||u.hash||u.username||u.password)throw new DriveError('UNCONFIGURED');}
 async start(project:string){z.uuid().parse(project);const existing=await this.scope.project(project);const binding=existing?.id??randomUUID();return authorizationRequest(this.config,this.userId,existing?.accountId??null,{put:async r=>{await this.vault.transaction('state:'+r.stateHash,async tx=>{if(tx.value)throw new DriveError('CONFLICT');tx.put({project,binding,expectedAccount:r.expectedAccount,folder:existing?.folderId??null,verifier:r.verifier},r.expiresAt);});},consume:async()=>{throw new DriveError('FORBIDDEN');}});}
 private async token(body:Record<string,string>){let r:Response;try{r=await this.http('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({...body,client_id:this.config.clientId,client_secret:this.config.clientSecret}),redirect:'error',cache:'no-store',signal:AbortSignal.timeout(15000)});}catch{throw new DriveError('RETRYABLE');}if(!r.ok)throw new DriveError(r.status===400||r.status===401?'RECONNECT':'RETRYABLE');const d=await r.json();if(typeof d.access_token!=='string'||!d.access_token||!Number.isSafeInteger(d.expires_in)||d.expires_in<1||d.expires_in>86400)throw new DriveError('RECONNECT');if(d.scope!==undefined&&(typeof d.scope!=='string'||d.scope.split(' ').filter(Boolean).join(' ')!==DRIVE_SCOPE))throw new DriveError('RECONNECT');return d as {access_token:string;refresh_token?:string;expires_in:number;scope?:string};}
 private async google(access:string,path:string,init:RequestInit={}){let r:Response;try{r=await this.http('https://www.googleapis.com/drive/v3/'+path,{...init,headers:{...init.headers,Authorization:'Bearer '+access},redirect:'error',cache:'no-store',signal:AbortSignal.timeout(15000)});}catch{throw new DriveError('RETRYABLE');}if(!r.ok)throw new DriveError(r.status===401?'RECONNECT':'RETRYABLE');return r.json();}
 async callback(state:string,code:string){if(!/^[A-Za-z0-9_-]{43}$/.test(state)||!code||code.length>4096)throw new DriveError('FORBIDDEN');const record=await this.vault.transaction('state:'+createHash('sha256').update(state).digest('hex'),async tx=>{const value=tx.value;tx.remove();return value;});const parsed=stateSchema.safeParse(record);if(!parsed.success)throw new DriveError('FORBIDDEN');const s=parsed.data;const result=await this.vault.transaction('state:connect_'+s.project,async()=>{const existing=await this.scope.project(s.project);if((existing?.id??null)!==(s.folder?s.binding:null))throw new DriveError('CONFLICT');
  const t=await this.token({grant_type:'authorization_code',code,code_verifier:s.verifier,redirect_uri:this.config.redirectUri});if(t.scope!==DRIVE_SCOPE||!t.refresh_token)throw new DriveError('RECONNECT');const about=await this.google(t.access_token,'about?fields=user(permissionId)');const account=about.user?.permissionId;if(typeof account!=='string'||!account)throw new DriveError('RECONNECT');if(s.expectedAccount&&account!==s.expectedAccount)throw new DriveError('WRONG_ACCOUNT');
  let folder=s.folder;if(!folder){const f=await this.google(t.access_token,'files?fields=id',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Research originals',mimeType:'application/vnd.google-apps.folder',appProperties:{kgFolder:'originals'}})});if(typeof f.id!=='string'||!f.id)throw new DriveError('RETRYABLE');folder=f.id;}
  const folderMeta=await this.google(t.access_token,'files/'+encodeURIComponent(folder!)+ '?fields=id,mimeType,trashed,ownedByMe,shared,appProperties');if(folderMeta.id!==folder||folderMeta.mimeType!=='application/vnd.google-apps.folder'||folderMeta.trashed||folderMeta.ownedByMe!==true||folderMeta.shared!==false||folderMeta.appProperties?.kgFolder!=='originals')throw new DriveError('FORBIDDEN');
  await this.scope.bind(s.binding,s.project,account,folder!);return {accessToken:t.access_token,refreshToken:t.refresh_token,expiresAt:Date.now()+t.expires_in*1000,accountId:account};});
  await this.vault.transaction('token:'+s.binding,async tx=>{tx.put(result,Date.now()+365*86400000);});return s.project;
 }
 async access(bindingId:string){z.uuid().parse(bindingId);const grant=await this.vault.transaction('token:'+bindingId,async tx=>{const p=tokenSchema.safeParse(tx.value);if(!p.success)return null;let t=p.data;if(t.expiresAt<=Date.now()+60000){try{const r=await this.token({grant_type:'refresh_token',refresh_token:t.refreshToken});t={...t,accessToken:r.access_token,refreshToken:r.refresh_token??t.refreshToken,expiresAt:Date.now()+r.expires_in*1000};tx.put(t,Date.now()+365*86400000);}catch(e){if(e instanceof DriveError&&e.code==='RECONNECT'){tx.remove();return null;}throw e;}}return {accessToken:t.accessToken,scopes:[DRIVE_SCOPE]};});if(!grant)throw new DriveError('RECONNECT');return grant;}
}
export function encryptedSessions(vault:SecretVault):SessionVault{return {once:(id,expiresAt,create)=>vault.transaction('session:'+id,async tx=>{if(typeof tx.value==='string')return sessionURL(tx.value);if(expiresAt<=Date.now())throw new DriveError('EXPIRED');const value=sessionURL(await create());tx.put(value,expiresAt);return value;})};}
