import 'server-only';
import {researchDAL} from '../dal';
import {userClient} from '../supabase/client';
import {AppError,uuid} from '../../application/models';
export type QueuePaper={id:string;title:string;authors:string;year:number|null;canonical_url:string|null;priority:number|null;investigation_reason:string|null;doi:string|null};
export async function pdfQueue(projectId:string){await (await researchDAL()).project(projectId);const client=await userClient();
 const {data,error}=await client.from('papers').select('id,title,authors,year,canonical_url,priority,investigation_reason').eq('project_id',projectId).is('archived_at',null).order('priority',{ascending:true,nullsFirst:false});if(error)throw new AppError('UNAVAILABLE');
 const docs=await client.from('paper_documents').select('paper_id,document_asset_id').eq('project_id',projectId).eq('role','main_text');if(docs.error)throw new AppError('UNAVAILABLE');
 const ids=await client.from('paper_identifiers').select('paper_id,normalized_value').eq('project_id',projectId).eq('provider','doi');if(ids.error)throw new AppError('UNAVAILABLE');
 const assets=await client.from('document_assets').select('id').eq('project_id',projectId).eq('upload_state','verified');if(assets.error)throw new AppError('UNAVAILABLE');const verified=new Set(assets.data.map(a=>a.id));
 const has=new Set(docs.data.filter(d=>verified.has(d.document_asset_id)).map(d=>d.paper_id));return data.filter(p=>!has.has(p.id)).map(p=>({...p,doi:ids.data.find(d=>d.paper_id===p.id)?.normalized_value??null})) as QueuePaper[];
}
export async function paperPDFs(projectId:string,paperId:string){await (await researchDAL()).paper(projectId,paperId);const client=await userClient();const {data,error}=await client.from('paper_documents').select('id,document_asset_id,edition_label,acquired_from').eq('project_id',projectId).eq('paper_id',paperId);if(error)throw new AppError('UNAVAILABLE');const assets=await client.from('document_assets').select('id,physical_page_count,sha256').eq('project_id',projectId).eq('upload_state','verified');if(assets.error)throw new AppError('UNAVAILABLE');return data.map(d=>({...d,pageCount:assets.data.find(a=>a.id===d.document_asset_id)?.physical_page_count??null,sha256:assets.data.find(a=>a.id===d.document_asset_id)?.sha256??null}));}
export async function verifiedAsset(projectId:string,paperId:string,assetId:string){if(!uuid.safeParse(assetId).success)throw new AppError('INVALID');await (await researchDAL()).paper(projectId,paperId);const client=await userClient();const link=await client.from('paper_documents').select('id').eq('project_id',projectId).eq('paper_id',paperId).eq('document_asset_id',assetId).limit(1);if(link.error||!link.data?.length)throw new AppError('FORBIDDEN');const {data,error}=await client.from('document_assets').select('storage_path').eq('project_id',projectId).eq('id',assetId).eq('upload_state','verified').maybeSingle();if(error||!data)throw new AppError('FORBIDDEN');return {client,path:data.storage_path as string};}

export async function paperAttempts(projectId:string,paperId:string){await (await researchDAL()).paper(projectId,paperId);const client=await userClient();const {data,error}=await client.from('upload_intents').select('id,original_filename,edition_label,state,expires_at').eq('project_id',projectId).eq('paper_id',paperId).order('created_at',{ascending:false});if(error)throw new AppError('UNAVAILABLE');return data;}
