import 'server-only';import {z} from 'zod';import type {SupabaseClient} from '@supabase/supabase-js';
import {AppError} from '../../application/models';import type {SearchRun,ResearchQuestion,AcquisitionTask,DiscoveryKind,CandidateDecision,DiscoveryInfo} from '../../application/literature';import {LiteratureProviders} from './providers';import {userClient} from '../supabase/client';import {researchDAL} from '../dal';
const querySchema=z.string().trim().min(2).max(500),reasonSchema=z.string().trim().min(1).max(2000);const providers=new LiteratureProviders();
function fail(error:{message:string}|null){if(error)throw new AppError(error.message==='KG_REJECTED'?'REJECTED':error.message==='KG_INVALID'?'INVALID':error.message==='KG_CONFLICT'?'CONFLICT':error.message==='KG_DUPLICATE_TITLE'?'DUPLICATE_TITLE':error.message==='KG_FORBIDDEN'?'FORBIDDEN':error.message==='KG_ARCHIVED'?'ARCHIVED':'UNAVAILABLE');}
export class LiteratureDAL{
 constructor(private client:SupabaseClient,private authorize:(p:string,active:boolean)=>Promise<void>,private adapters:Pick<LiteratureProviders,'search'> & Partial<Pick<LiteratureProviders,'discover'>>=providers){}
 private async scope(p:string,active=false){z.uuid().parse(p);await this.authorize(p,active);}
 async overview(project:string){await this.scope(project);const [q,s,t,selections,revisions,expansions,relations]=await Promise.all([this.client.from('research_questions').select('id,question').eq('project_id',project).order('created_at',{ascending:false}),this.client.from('literature_searches').select('id,query,question_id,created_at,payload').eq('project_id',project).order('created_at',{ascending:false}).limit(20),this.client.from('acquisition_tasks').select('id,paper_id,question_id,priority,status,reason,revision').eq('project_id',project).order('priority',{ascending:true}),this.client.from('literature_selections').select('id,search_id,candidate_index,reason,priority,paper_id').eq('project_id',project).order('created_at',{ascending:false}).limit(100),this.client.from('question_revisions').select('question_id,data,revision').eq('project_id',project).order('revision',{ascending:false}),this.client.from('literature_expansions').select('search_id,seed_paper_id,kind,depth,parent_search_id').eq('project_id',project).order('created_at',{ascending:false}).limit(100),this.client.from('paper_relations').select('id,source_paper_id,target_paper_id,relation,search_id,providers,created_at').eq('project_id',project).order('created_at',{ascending:false}).limit(100)]);fail(expansions.error);fail(relations.error);fail(revisions.error);fail(selections.error);fail(q.error);fail(s.error);fail(t.error);return {decisions:await this.decisions(project),expansions:expansions.data as DiscoveryInfo[],relations:relations.data as {id:string;source_paper_id:string;target_paper_id:string;relation:'cites'|'related_to';search_id:string;providers:string[];created_at:string}[],selections:selections.data as {id:string;search_id:string;candidate_index:number;reason:string;priority:number;paper_id:string}[],questions:(q.data as ResearchQuestion[]).map(q=>({...q,question:revisions.data?.find(r=>r.question_id===q.id)?.data.question??q.question})),searches:s.data as SearchRun[],tasks:t.data as AcquisitionTask[]};}
 private async decisions(project:string){const rows:CandidateDecision[]=[];let count:number|null=null;for(let i=0;i<100;i++){const r=await this.client.from('candidate_decisions').select('id,search_id,candidate_index,doi,semantic_id,decision,reason,revision',{count:'exact'}).eq('project_id',project).order('revision').range(rows.length,rows.length+499);fail(r.error);if(r.count==null||r.count>10000||count!==null&&count!==r.count)throw new AppError('UNAVAILABLE');count=r.count;if(!r.data?.length&&rows.length<count)throw new AppError('UNAVAILABLE');rows.push(...r.data as CandidateDecision[]);if(rows.length===count)return rows;}throw new AppError('UNAVAILABLE');}
 async decide(project:string,id:string,search:string,index:number,expected:string|null,decision:string,reason:string){await this.scope(project,true);[id,search].forEach(v=>z.uuid().parse(v));z.uuid().nullable().parse(expected);z.number().int().min(0).max(19).parse(index);z.enum(['rejected','reopened']).parse(decision);reasonSchema.parse(reason);const r=await this.client.rpc('decide_literature_candidate',{p_project:project,p_id:id,p_search:search,p_index:index,p_expected:expected,p_decision:decision,p_reason:reason});fail(r.error);const d=await this.client.from('candidate_decisions').select('id,search_id,candidate_index,doi,semantic_id,decision,reason,revision').eq('project_id',project).eq('id',r.data).single();fail(d.error);return d.data as CandidateDecision;}
 async discover(project:string,id:string,seed:string,kind:DiscoveryKind,parent:string|null,question:string|null){
  await this.scope(project,true);[id,seed].forEach(v=>z.uuid().parse(v));z.enum(['references','citations','related']).parse(kind);z.uuid().nullable().parse(parent);z.uuid().nullable().parse(question);
  const old=await this.client.from('literature_searches').select('id,query,question_id,created_at,payload').eq('project_id',project).eq('id',id).maybeSingle();fail(old.error);
  if(old.data){const e=await this.client.from('literature_expansions').select('seed_paper_id,kind,parent_search_id').eq('project_id',project).eq('search_id',id).maybeSingle();fail(e.error);if(!e.data||e.data.seed_paper_id!==seed||e.data.kind!==kind||e.data.parent_search_id!==parent||old.data.question_id!==question)throw new AppError('CONFLICT');return old.data as SearchRun;}
  const p=await this.client.from('papers').select('id,archived_at').eq('project_id',project).eq('id',seed).maybeSingle();fail(p.error);if(!p.data||p.data.archived_at)throw new AppError('FORBIDDEN');
  if(question){const q=await this.client.from('research_questions').select('id').eq('project_id',project).eq('id',question).maybeSingle();fail(q.error);if(!q.data)throw new AppError('FORBIDDEN');}
  if(parent){const [e,s]=await Promise.all([this.client.from('literature_expansions').select('depth').eq('project_id',project).eq('search_id',parent).maybeSingle(),this.client.from('literature_selections').select('id').eq('project_id',project).eq('search_id',parent).eq('paper_id',seed).limit(1)]);fail(e.error);fail(s.error);if(!e.data||e.data.depth>=2||!s.data?.length)throw new AppError('INVALID');}
  const identifiers=await this.client.from('paper_identifiers').select('provider,normalized_value').eq('project_id',project).eq('paper_id',seed);fail(identifiers.error);const ids={doi:identifiers.data?.find(i=>i.provider==='doi')?.normalized_value??'',semanticId:identifiers.data?.find(i=>i.provider==='semantic_scholar')?.normalized_value??''};if(!ids.doi&&!ids.semanticId)throw new AppError('INVALID');
  if(!this.adapters.discover)throw new AppError('UNAVAILABLE');const payload=await this.adapters.discover(kind,ids);const r=await this.client.rpc('record_literature_expansion',{p_project:project,p_id:id,p_seed:seed,p_kind:kind,p_parent:parent,p_question:question,p_payload:payload});fail(r.error);return r.data as SearchRun;
 }
 async details(project:string,paper:string,revision:number,authors:string,abstract:string,url:string,relevance:string){await this.scope(project,true);z.uuid().parse(paper);z.number().int().positive().parse(revision);z.string().max(1000).parse(authors);z.string().max(20000).parse(abstract);z.string().max(4000).parse(relevance);z.string().max(2000).parse(url);if(url){const u=new URL(url);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw new AppError('INVALID');}const r=await this.client.rpc('edit_paper_details',{p_project:project,p_paper:paper,p_expected:revision,p_authors:authors,p_abstract:abstract,p_url:url,p_relevance:relevance});fail(r.error);return r.data as string;}

 async question(project:string,id:string,question:string){await this.scope(project,true);z.uuid().parse(id);reasonSchema.parse(question);const r=await this.client.rpc('create_research_question',{p_project:project,p_id:id,p_question:question});fail(r.error);return r.data as string;}
 async search(project:string,id:string,query:string,question:string|null){await this.scope(project,true);z.uuid().parse(id);const normalized=querySchema.parse(query);z.uuid().nullable().parse(question);if(question){const q=await this.client.from('research_questions').select('id').eq('project_id',project).eq('id',question).maybeSingle();fail(q.error);if(!q.data)throw new AppError('FORBIDDEN');}const old=await this.client.from('literature_searches').select('id,query,question_id,created_at,payload').eq('project_id',project).eq('id',id).maybeSingle();fail(old.error);if(old.data){if(old.data.query!==normalized||old.data.question_id!==question)throw new AppError('CONFLICT');return old.data as SearchRun;}const payload=await this.adapters.search(normalized);const saved=await this.client.rpc('record_literature_search',{p_project:project,p_id:id,p_query:normalized,p_question:question,p_payload:payload});fail(saved.error);return saved.data as SearchRun;}
 async select(project:string,id:string,search:string,index:number,reason:string,priority:number){await this.scope(project,true);z.uuid().parse(id);z.uuid().parse(search);z.number().int().min(0).max(19).parse(index);reasonSchema.parse(reason);z.number().int().min(1).max(3).parse(priority);const r=await this.client.rpc('select_literature_candidate',{p_project:project,p_id:id,p_search:search,p_index:index,p_reason:reason,p_priority:priority});fail(r.error);return r.data as {paper_id:string;task_id:string};}
 async task(project:string,id:string,paper:string,question:string|null,revision:number,priority:number,status:string,reason:string){await this.scope(project,true);z.uuid().parse(id);z.uuid().parse(paper);z.uuid().nullable().parse(question);z.number().int().nonnegative().parse(revision);z.number().int().min(1).max(3).parse(priority);z.enum(['needed','requested','blocked','deferred']).parse(status);reasonSchema.parse(reason);const r=await this.client.rpc('set_acquisition_task',{p_project:project,p_id:id,p_paper:paper,p_question:question,p_expected:revision,p_priority:priority,p_status:status,p_reason:reason});fail(r.error);return r.data as string;}
}
export async function literatureDAL(){return new LiteratureDAL(await userClient(),async(p,active)=>{const project=await (await researchDAL()).project(p);if(active&&project.archived_at)throw new AppError('ARCHIVED');});}
