import 'server-only';import {z} from 'zod';import type {SupabaseClient} from '@supabase/supabase-js';
import {AppError} from '../../application/models';import type {SearchRun,ResearchQuestion,AcquisitionTask} from '../../application/literature';import {LiteratureProviders} from './providers';import {userClient} from '../supabase/client';import {researchDAL} from '../dal';
const querySchema=z.string().trim().min(2).max(500),reasonSchema=z.string().trim().min(1).max(2000);const providers=new LiteratureProviders();
function fail(error:{message:string}|null){if(error)throw new AppError(error.message==='KG_CONFLICT'?'CONFLICT':error.message==='KG_DUPLICATE_TITLE'?'DUPLICATE_TITLE':error.message==='KG_FORBIDDEN'?'FORBIDDEN':error.message==='KG_ARCHIVED'?'ARCHIVED':'UNAVAILABLE');}
export class LiteratureDAL{
 constructor(private client:SupabaseClient,private authorize:(p:string,active:boolean)=>Promise<void>,private adapters:Pick<LiteratureProviders,'search'>=providers){}
 private async scope(p:string,active=false){z.uuid().parse(p);await this.authorize(p,active);}
 async overview(project:string){await this.scope(project);const [q,s,t,selections,revisions]=await Promise.all([this.client.from('research_questions').select('id,question').eq('project_id',project).order('created_at',{ascending:false}),this.client.from('literature_searches').select('id,query,question_id,created_at,payload').eq('project_id',project).order('created_at',{ascending:false}).limit(20),this.client.from('acquisition_tasks').select('id,paper_id,question_id,priority,status,reason,revision').eq('project_id',project).order('priority',{ascending:true}),this.client.from('literature_selections').select('id,search_id,candidate_index,reason,priority,paper_id').eq('project_id',project).order('created_at',{ascending:false}).limit(100),this.client.from('question_revisions').select('question_id,data,revision').eq('project_id',project).order('revision',{ascending:false})]);fail(revisions.error);fail(selections.error);fail(q.error);fail(s.error);fail(t.error);return {selections:selections.data as {id:string;search_id:string;candidate_index:number;reason:string;priority:number;paper_id:string}[],questions:(q.data as ResearchQuestion[]).map(q=>({...q,question:revisions.data?.find(r=>r.question_id===q.id)?.data.question??q.question})),searches:s.data as SearchRun[],tasks:t.data as AcquisitionTask[]};}
 async question(project:string,id:string,question:string){await this.scope(project,true);z.uuid().parse(id);reasonSchema.parse(question);const r=await this.client.rpc('create_research_question',{p_project:project,p_id:id,p_question:question});fail(r.error);return r.data as string;}
 async search(project:string,id:string,query:string,question:string|null){await this.scope(project,true);z.uuid().parse(id);const normalized=querySchema.parse(query);z.uuid().nullable().parse(question);if(question){const q=await this.client.from('research_questions').select('id').eq('project_id',project).eq('id',question).maybeSingle();fail(q.error);if(!q.data)throw new AppError('FORBIDDEN');}const old=await this.client.from('literature_searches').select('id,query,question_id,created_at,payload').eq('project_id',project).eq('id',id).maybeSingle();fail(old.error);if(old.data){if(old.data.query!==normalized||old.data.question_id!==question)throw new AppError('CONFLICT');return old.data as SearchRun;}const payload=await this.adapters.search(normalized);const saved=await this.client.rpc('record_literature_search',{p_project:project,p_id:id,p_query:normalized,p_question:question,p_payload:payload});fail(saved.error);return saved.data as SearchRun;}
 async select(project:string,id:string,search:string,index:number,reason:string,priority:number){await this.scope(project,true);z.uuid().parse(id);z.uuid().parse(search);z.number().int().min(0).max(19).parse(index);reasonSchema.parse(reason);z.number().int().min(1).max(3).parse(priority);const r=await this.client.rpc('select_literature_candidate',{p_project:project,p_id:id,p_search:search,p_index:index,p_reason:reason,p_priority:priority});fail(r.error);return r.data as {paper_id:string;task_id:string};}
 async task(project:string,id:string,paper:string,question:string|null,revision:number,priority:number,status:string,reason:string){await this.scope(project,true);z.uuid().parse(id);z.uuid().parse(paper);z.uuid().nullable().parse(question);z.number().int().nonnegative().parse(revision);z.number().int().min(1).max(3).parse(priority);z.enum(['needed','requested','blocked','deferred']).parse(status);reasonSchema.parse(reason);const r=await this.client.rpc('set_acquisition_task',{p_project:project,p_id:id,p_paper:paper,p_question:question,p_expected:revision,p_priority:priority,p_status:status,p_reason:reason});fail(r.error);return r.data as string;}
}
export async function literatureDAL(){return new LiteratureDAL(await userClient(),async(p,active)=>{const project=await (await researchDAL()).project(p);if(active&&project.archived_at)throw new AppError('ARCHIVED');});}
