import 'server-only';
import {candidateSchema,candidateURL,mergeCandidates,type Candidate,type ProviderResult} from '../../application/literature';
import {normalizeDoi} from '../../application/models';
const text=(v:unknown,max:number)=>typeof v==='string'?v.replace(/<[^>]*>/g,'').trim().slice(0,max):'';
const doi=(v:unknown)=>{const d=normalizeDoi(text(v,1000));return /^10\.[0-9]{4,9}\/[^\s<>]+$/.test(d)?d:'';};
const year=(v:unknown)=>typeof v==='number'&&Number.isInteger(v)&&v>=1000&&v<=new Date().getUTCFullYear()+1?v:null;
const record=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
export class LiteratureProviders{
 private cooldown=new Map<string,number>();
 constructor(private http:typeof fetch=fetch){}
 private async request(provider:ProviderResult['provider'],query:string):Promise<ProviderResult>{const result=(status:ProviderResult['status'],items:Candidate[]=[],retryAfter:number|null=null)=>({provider,status,items,retryAfter});const wait=(this.cooldown.get(provider)??0)-Date.now();if(wait>0)return result('rate_limited',[],Math.ceil(wait/1000));const url=new URL(provider==='crossref'?'https://api.crossref.org/works':'https://api.semanticscholar.org/graph/v1/paper/search');url.searchParams.set(provider==='crossref'?'query.bibliographic':'query',query);if(provider==='crossref')url.searchParams.set('rows','10');else{url.searchParams.set('limit','10');url.searchParams.set('fields','title,authors,year,venue,url,externalIds,abstract');}
  try{const r=await this.http(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(12000),redirect:'error',cache:'no-store'});if(r.status===429){const retry=r.headers.get('retry-after')??'';const seconds=Math.min(3600,Math.max(1,Number(retry)||Math.ceil((Date.parse(retry)-Date.now())/1000)||60));this.cooldown.set(provider,Date.now()+seconds*1000);return result('rate_limited',[],seconds);}if(r.status===401||r.status===403)return result('access_denied');if(!r.ok)return result('unavailable');const reader=r.body?.getReader();if(!reader)return result('invalid_response');const parts:Uint8Array[]=[];let size=0;try{while(true){const chunk=await reader.read();if(chunk.done)break;size+=chunk.value.length;if(size>1048576)return result('invalid_response');parts.push(chunk.value);}}finally{await reader.cancel().catch(()=>{});}const body=record(JSON.parse(Buffer.concat(parts,size).toString('utf8')));const rows=provider==='crossref'?record(body.message).items:body.data;if(!Array.isArray(rows))return result('invalid_response');const items:Candidate[]=[];for(const raw of rows.slice(0,10)){const x=record(raw),authors=Array.isArray(x.authors)?x.authors:Array.isArray(x.author)?x.author:[];const dates=record(x.published)['date-parts'];const c={title:text(provider==='crossref'&&Array.isArray(x.title)?x.title[0]:x.title,500),authors:authors.map(a=>{const author=record(a);return provider==='crossref'?text([author.given,author.family].filter(v=>typeof v==='string').join(' '),200):text(author.name,200);}).filter(Boolean).join(', ').slice(0,1000),journal:text(provider==='crossref'&&Array.isArray(x['container-title'])?x['container-title'][0]:x.venue,500),year:year(provider==='crossref'&&Array.isArray(dates)&&Array.isArray(dates[0])?dates[0][0]:x.year),doi:doi(provider==='crossref'?x.DOI:record(x.externalIds).DOI),semanticId:provider==='semantic_scholar'?text(x.paperId,255):'',url:candidateURL(text(provider==='crossref'?x.URL:x.url,2000)),abstract:text(x.abstract,2000),sources:[provider]};const parsed=candidateSchema.safeParse(c);if(parsed.success&&(parsed.data.doi||parsed.data.semanticId))items.push(parsed.data);}return result('ok',items);
  }catch{return result('unavailable');}
 }
 async search(query:string):Promise<{providers:ProviderResult[];candidates:Candidate[]}>{const providers=await Promise.all([this.request('semantic_scholar',query),this.request('crossref',query)]);return {providers,candidates:mergeCandidates(providers)};}
}
