-- Task 3 candidate, generated by CLI 2.119.0; no verifier login or membership provisioned.
begin;
alter table public.papers add column authors text not null default '' check(length(authors)<=4000);
alter table public.document_assets add column physical_page_count integer check(physical_page_count between 1 and 2000),add column verifier_version text;
create table public.upload_intents(
 id uuid primary key,project_id uuid not null references public.projects(id),paper_id uuid not null,
 created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),expires_at timestamptz not null default now()+interval '24 hours',
 original_filename text not null check(length(original_filename) between 1 and 255),expected_size bigint not null check(expected_size between 1 and 4194304),expected_hash text check(expected_hash ~ '^[a-f0-9]{64}$'),
 edition_label text not null check(length(edition_label) between 1 and 200),acquired_from text not null check(length(acquired_from) between 1 and 2000),access_basis text not null check(length(access_basis) between 1 and 500),
 state text not null default 'awaiting' check(state in ('awaiting','failed','cancelled','finalized')),result_asset_id uuid,result_document_id uuid,matched_known_bytes boolean,
 foreign key(project_id,paper_id) references public.papers(project_id,id),foreign key(project_id,result_asset_id) references public.document_assets(project_id,id),foreign key(project_id,result_document_id) references public.paper_documents(project_id,id),
 check((state='finalized')=(result_asset_id is not null and result_document_id is not null and matched_known_bytes is not null)));
alter table public.upload_intents enable row level security;
revoke all on public.upload_intents from public,anon,authenticated,service_role;
grant select on public.upload_intents to authenticated;
create policy owner_read on public.upload_intents for select to authenticated using(kg_private.has_role(project_id,array['owner']));
create trigger audit_change after insert or update on public.upload_intents for each row execute function kg_private.capture_audit();
create index upload_intents_paper on public.upload_intents(project_id,paper_id);
create function public.begin_pdf_upload(p_id uuid,p_project uuid,p_paper uuid,p_filename text,p_size bigint,p_hash text,p_edition text,p_source text,p_access text) returns uuid language plpgsql security definer set search_path='' as $$
declare old public.upload_intents;
begin
 perform pg_advisory_xact_lock(hashtextextended(p_project::text,0));perform kg_private.require_owner(p_project,true);
 if not exists(select from public.papers where project_id=p_project and id=p_paper and archived_at is null) then raise exception 'KG_FORBIDDEN'; end if;
 select * into old from public.upload_intents where id=p_id;
 if found then
  if old.project_id is distinct from p_project or old.paper_id is distinct from p_paper or old.original_filename is distinct from p_filename or old.expected_size is distinct from p_size or old.expected_hash is distinct from p_hash or old.edition_label is distinct from p_edition or old.acquired_from is distinct from p_source or old.access_basis is distinct from p_access or old.created_by is distinct from auth.uid() then raise exception 'KG_CONFLICT'; end if;return old.id;
 end if;
 insert into public.upload_intents(id,project_id,paper_id,created_by,original_filename,expected_size,expected_hash,edition_label,acquired_from,access_basis) values(p_id,p_project,p_paper,auth.uid(),p_filename,p_size,p_hash,p_edition,p_source,p_access);return p_id;
end; $$;
create function public.mark_pdf_upload(p_id uuid,p_state text) returns void language plpgsql security definer set search_path='' as $$
declare i public.upload_intents;
begin
 select * into i from public.upload_intents where id=p_id;if not found then raise exception 'KG_FORBIDDEN'; end if;
 perform pg_advisory_xact_lock(hashtextextended(i.project_id::text,0));perform kg_private.require_owner(i.project_id,true);
 select * into i from public.upload_intents where id=p_id for update;
 if i.state=p_state and p_state in ('failed','cancelled') then return;end if;
 if p_state not in ('failed','cancelled') or p_state is null or i.state in ('finalized','cancelled') then raise exception 'KG_CONFLICT'; end if;
 update public.upload_intents set state=p_state where id=p_id;
end; $$;
revoke all on function public.begin_pdf_upload(uuid,uuid,uuid,text,bigint,text,text,text,text),public.mark_pdf_upload(uuid,text) from public,anon,authenticated,service_role;
grant execute on function public.begin_pdf_upload(uuid,uuid,uuid,text,bigint,text,text,text,text),public.mark_pdf_upload(uuid,text) to authenticated;
-- Isolated verifier capability. Never grant membership to any app role.
create role kg_pdf_verifier nologin noinherit nobypassrls;
grant usage on schema public,kg_private to kg_pdf_verifier;
grant execute on function kg_private.caller_uid(),kg_private.require_owner(uuid,boolean),kg_private.has_role(uuid,text[]) to kg_pdf_verifier;
grant select on public.projects,public.papers,public.document_assets,public.paper_documents,public.upload_intents to kg_pdf_verifier;
grant insert on public.document_assets,public.paper_documents to kg_pdf_verifier;
grant update(state,result_asset_id,result_document_id,matched_known_bytes) on public.upload_intents to kg_pdf_verifier;
alter policy member_read on public.projects to authenticated,kg_metadata_writer,kg_pdf_verifier;
alter policy member_read on public.papers to authenticated,kg_metadata_writer,kg_pdf_verifier;
alter policy member_read on public.document_assets to authenticated,kg_pdf_verifier;
alter policy member_read on public.paper_documents to authenticated,kg_pdf_verifier;
alter policy owner_read on public.upload_intents to authenticated,kg_pdf_verifier;
create policy verifier_intent_update on public.upload_intents for update to kg_pdf_verifier using(kg_private.has_role(project_id,array['owner'])) with check(kg_private.has_role(project_id,array['owner']));
create policy verifier_asset_insert on public.document_assets for insert to kg_pdf_verifier with check(created_by=kg_private.caller_uid() and kg_private.has_role(project_id,array['owner']) and upload_state='verified' and physical_page_count is not null and verifier_version='pdf-lib@1.17.1');
create policy verifier_document_insert on public.paper_documents for insert to kg_pdf_verifier with check(created_by=kg_private.caller_uid() and kg_private.has_role(project_id,array['owner']));
create function kg_private.finalize_pdf(p_id uuid,p_hash text,p_size bigint,p_pages integer) returns jsonb language plpgsql security invoker set search_path='' as $$
declare i public.upload_intents;asset uuid;doc uuid;matched boolean;
begin
 select * into i from public.upload_intents where id=p_id;if not found then raise exception 'KG_FORBIDDEN'; end if;
 perform pg_advisory_xact_lock(hashtextextended(i.project_id::text,0));perform kg_private.require_owner(i.project_id,true);
 select * into i from public.upload_intents where id=p_id for update;
 if not exists(select from public.papers where project_id=i.project_id and id=i.paper_id and archived_at is null) then raise exception 'KG_FORBIDDEN'; end if;
 if p_hash is null or p_hash!~'^[a-f0-9]{64}$' or p_size is distinct from i.expected_size or (i.expected_hash is not null and i.expected_hash<>p_hash) or p_pages is null or p_pages not between 1 and 2000 then raise exception 'KG_MISMATCH'; end if;
 if i.state='finalized' then
  if not exists(select from public.document_assets where id=i.result_asset_id and sha256=p_hash and byte_size=p_size and physical_page_count=p_pages) then raise exception 'KG_CONFLICT'; end if;
  return jsonb_build_object('assetId',i.result_asset_id,'documentId',i.result_document_id,'matchedKnownBytes',i.matched_known_bytes);
 end if;
 if i.state='cancelled' then raise exception 'KG_CANCELLED'; end if;if i.expires_at<=now() then raise exception 'KG_EXPIRED'; end if;
 select id into asset from public.document_assets where project_id=i.project_id and sha256=p_hash and upload_state='verified';matched:=asset is not null;
 if asset is null then
  asset:=i.id;
  insert into public.document_assets(id,project_id,storage_bucket,storage_path,sha256,byte_size,mime,original_filename,upload_state,verified_at,created_by,physical_page_count,verifier_version) values(asset,i.project_id,'research-originals',i.project_id::text||'/'||i.id::text||'/original.pdf',p_hash,p_size,'application/pdf',i.original_filename,'verified',now(),kg_private.caller_uid(),p_pages,'pdf-lib@1.17.1');
 elsif not exists(select from public.document_assets where id=asset and byte_size=p_size and physical_page_count=p_pages) then raise exception 'KG_MISMATCH';end if;
 select id into doc from public.paper_documents where project_id=i.project_id and paper_id=i.paper_id and document_asset_id=asset and role='main_text';
 if doc is null then insert into public.paper_documents(project_id,paper_id,document_asset_id,role,edition_label,acquired_at,acquired_from,access_basis,created_by) values(i.project_id,i.paper_id,asset,'main_text',i.edition_label,i.created_at,i.acquired_from,i.access_basis,kg_private.caller_uid()) returning id into doc;end if;
 update public.upload_intents set state='finalized',result_asset_id=asset,result_document_id=doc,matched_known_bytes=matched where id=i.id;
 return jsonb_build_object('assetId',asset,'documentId',doc,'matchedKnownBytes',matched);
end; $$;
revoke all on function kg_private.finalize_pdf(uuid,text,bigint,integer) from public,anon,authenticated,service_role;
grant execute on function kg_private.finalize_pdf(uuid,text,bigint,integer) to kg_pdf_verifier;
-- Invoker-only: the unprovisioned worker requires this narrow role, never service_role.
create function kg_private.pdf_object_allowed(object_name text,for_insert boolean) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select from public.upload_intents i join public.projects p on p.id=i.project_id join public.papers paper on paper.id=i.paper_id and paper.project_id=p.id where object_name=i.project_id::text||'/'||i.id::text||'/original.pdf' and p.owner_user_id=auth.uid() and kg_private.has_role(p.id,array['owner']) and (not for_insert or (p.archived_at is null and paper.archived_at is null and i.state='awaiting' and i.expires_at>now())))
 or (not for_insert and exists(select from public.document_assets a join public.projects p on p.id=a.project_id where a.storage_path=object_name and p.owner_user_id=auth.uid() and kg_private.has_role(p.id,array['owner']) and a.upload_state='verified'));
$$;
revoke all on function kg_private.pdf_object_allowed(text,boolean) from public,anon,authenticated,service_role;
grant execute on function kg_private.pdf_object_allowed(text,boolean) to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('research-originals','research-originals',false,4194304,array['application/pdf']);
create policy kg_pdf_insert on storage.objects for insert to authenticated with check(bucket_id='research-originals' and kg_private.pdf_object_allowed(name,true));
create policy kg_pdf_insert_guard on storage.objects as restrictive for insert to authenticated with check(bucket_id<>'research-originals' or kg_private.pdf_object_allowed(name,true));
create policy kg_pdf_read on storage.objects for select to authenticated using(bucket_id='research-originals' and kg_private.pdf_object_allowed(name,false));
create policy kg_pdf_read_guard on storage.objects as restrictive for select to authenticated using(bucket_id<>'research-originals' or kg_private.pdf_object_allowed(name,false));
create policy kg_pdf_no_update on storage.objects as restrictive for update to authenticated,anon using(bucket_id<>'research-originals') with check(bucket_id<>'research-originals');
create policy kg_pdf_no_delete on storage.objects as restrictive for delete to authenticated,anon using(bucket_id<>'research-originals');
create policy kg_pdf_no_anon on storage.objects as restrictive for all to anon using(bucket_id<>'research-originals') with check(bucket_id<>'research-originals');
commit;
