'use client';
import {useEffect,useState} from 'react';
import type {ResearchCase} from '../domain/research-case';
import {depict,type Depiction} from '../client/chemical-renderer';
const messages:Record<string,string>={missing:'SMILES 未提供（構造図なし）',too_large:'描画上限超過（1024文字・128原子）',unsupported:'対応していない構造表記',invalid:'無効な SMILES（構造図は生成しません）',unavailable:'構造描画を利用できません',timeout:'構造描画を時間制限で停止しました'};
export function ChemicalStructure({compound,compact=false,sourceBase}:{sourceBase?:string;compound:ResearchCase['compounds'][number];compact?:boolean}){const smiles=compound.structure?.smiles;const [result,setResult]=useState<{input:typeof smiles;value:Depiction;url:string|null}|null>(null);useEffect(()=>{let alive=true,url:string|null=null;const timer=setTimeout(()=>{void depict(smiles).then(value=>{if(!alive)return;if(value.status==='ready')url=URL.createObjectURL(new Blob([value.svg],{type:'image/svg+xml'}));setResult({input:smiles,value,url});});},300);return()=>{clearTimeout(timer);alive=false;if(url)URL.revokeObjectURL(url);};},[smiles]);const current=result?.input===smiles?result:null;return <figure className={`chemical-structure${compact?' compact':''}`}><figcaption>{compound.name} · {compound.epistemic_status==='hypothetical'?'仮説構造':compound.epistemic_status==='observed'?'観測と記録された対象':'観測状態未指定'}{compound.structure?.representation==='transition_state'?' · 遷移状態（記録上の指定）':''}</figcaption>{current?.url?
// RDKit-generated SVG is isolated as an image, never inserted as executable markup.
// eslint-disable-next-line @next/next/no-img-element
<img src={current.url} width={300} height={210} alt={`${compound.name}：提供された SMILES の2D構造図`}/>:<p role="status">{current?messages[current.value.status]:'構造を検証中…'}</p>}{!compact&&<><p>提供された表記の描画であり、存在・反応機構の証明ではありません。{compound.node_type==='polymer'||compound.node_type==='polymer_site'?'有限部分構造のみ。重合度や鎖全体は推定しません。':''}</p><dl><dt>SMILES（原記録）</dt><dd>{smiles??'不明'}</dd><dt>InChI（記録値・意味検証なし）</dt><dd>{compound.structure?.inchi??'不明'}</dd><dt>CAS（書式・チェック桁のみ検証）</dt><dd>{compound.structure?.cas??'不明'}</dd><dt>構造の出典・帰属</dt><dd>{sourceBase&&compound.structure?.source_anchor_id?<a href={`${sourceBase}#source-${compound.structure.source_anchor_id}`}>原文・ページ・PDF 版を開く</a>:compound.structure?.source_anchor_id??'出典未接続'} · {compound.structure?.attribution??'not_reported'}</dd></dl>{current?.value.status==='ready'&&<small>RDKit {current.value.version} · {current.value.atoms} atoms · stereochemistry/charge from supplied SMILES</small>}</>}</figure>;}
export function ChemicalDetails({payload,reviewLabel,sourceBase}:{payload:ResearchCase;reviewLabel?:string;sourceBase?:string}){const d=payload.reaction.description;return <section className="panel"><h2>化学構造・反応の記述</h2><p>版の編集来歴: {reviewLabel??'編集中・未確認'}。描画成功は科学的確認ではありません。</p><div className="chemical-grid">{payload.compounds.map(c=><ChemicalStructure key={c.id} compound={c} sourceBase={sourceBase}/>)}</div><h3>反応型・機構</h3><dl><dt>反応型</dt><dd>{d?.reaction_type??'不明'}</dd><dt>可逆性（記録値・矢印の自動反転なし）</dt><dd>{d?.reversibility??'unknown'}</dd><dt>機構記述</dt><dd className="preserve-lines">{d?.description??'未提供'}</dd><dt>記述の出典・帰属</dt><dd>{sourceBase&&d?.source_anchor_id?<a href={`${sourceBase}#source-${d.source_anchor_id}`}>記述の原文・ページ・PDF 版を開く</a>:d?.source_anchor_id??'出典未接続'} · {d?.attribution??'not_reported'}</dd></dl></section>;}

export function StructureGlyph({compound,x,y}:{compound:ResearchCase['compounds'][number];x:number;y:number}){const smiles=compound.structure?.smiles;const [image,setImage]=useState<{input:typeof smiles;url:string|null;status:string}|null>(null);useEffect(()=>{let alive=true,url:string|null=null;void depict(smiles).then(r=>{if(!alive)return;if(r.status==='ready')url=URL.createObjectURL(new Blob([r.svg],{type:'image/svg+xml'}));setImage({input:smiles,url,status:r.status});});return()=>{alive=false;if(url)URL.revokeObjectURL(url);};},[smiles]);return image&&image.input===smiles&&image.url?<image href={image.url} x={x} y={y} width={144} height={96} aria-label={`${compound.name} の提供構造`}/>:<text x={x+5} y={y+45} fontSize="10">{image?.input===smiles?'構造図なし・詳細へ':'構造検証中…'}</text>;}
