'use client';
import {DriveViewer} from './drive-viewer';
import {useEffect,useState} from 'react';
import {DriveError,driveRecovery,safeDriveCode,type DriveReceipt} from '../application/drive';
type Attempt={id:string;filename:string;edition:string;size:number;expiresAt:number;cancelled:boolean;receipt:DriveReceipt|null};
export function DriveRecovery({projectId,paperId,enabled}:{projectId:string;paperId:string;enabled:boolean}){
 const [attempts,setAttempts]=useState<Attempt[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[checkedAt,setCheckedAt]=useState(0);
 useEffect(()=>{if(!enabled)return;const abort=new AbortController();void fetch('/api/drive',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'list',projectId,paperId}),signal:abort.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new DriveError(safeDriveCode(data));setAttempts(data);setCheckedAt(Date.now());}).catch(()=>{if(!abort.signal.aborted)setMessage('保存履歴を読み込めませんでした。再読み込みしてください。');});return ()=>abort.abort();},[projectId,paperId,enabled]);
 async function reconcile(id:string,action:'complete'|'cancel'){if(busy)return;setBusy(true);try{const r=await fetch('/api/drive',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id})});const data=await r.json();if(!r.ok)throw new DriveError(safeDriveCode(data));setAttempts(rows=>rows.map(a=>a.id===id?{...a,...(action==='complete'?{receipt:data}:{cancelled:true})}:a));setMessage(action==='complete'?'保存済み・未解析。出典・研究内容は未確認です。':'試行を取り消しました。新しい試行でファイルを選択してください。');}catch(e){setMessage(driveRecovery(e instanceof DriveError?e.code:'RETRYABLE'));}finally{setBusy(false);}}
 if(!enabled)return null;
 return <section className="panel"><h2>原本と転送履歴</h2><p>最新50件。転送済みの結果は再確認できます。再読み込み前に転送が完了していなければ、取り消して新しい試行を開始してください。</p>{attempts.map(a=><article key={a.id}><h3>{a.filename} · {a.edition}</h3><p>{a.receipt?'保存済み・未解析':a.cancelled?'取消済み':a.expiresAt<=checkedAt?'期限切れ':'結果未確認'} · {a.size} bytes</p>{a.receipt?<><DriveViewer intentId={a.id}/><dl><dt>原本の版</dt><dd>{a.receipt.revisionId}</dd><dt>SHA-256</dt><dd className="preserve-lines">{a.receipt.sha256}</dd><dt>出典ID</dt><dd>{a.receipt.id}</dd></dl></>:!a.cancelled&&<><button disabled={busy} onClick={()=>void reconcile(a.id,'complete')}>転送済みの保存結果を確認</button><button disabled={busy} onClick={()=>void reconcile(a.id,'cancel')}>試行を取り消す</button></>}</article>)}<p role="status">{message}</p></section>;
}
