'use client';
import {useRef,useState} from 'react';
import {DRIVE_TARGET_BYTES,DriveError,safeDriveCode,driveRecovery} from '../application/drive';
import {uploadDriveChunks} from '../application/drive-upload';
export function DriveUpload({projectId,paperId,enabled=false}:{projectId:string;paperId:string;enabled?:boolean}){
 const [file,setFile]=useState<File|null>(null),[edition,setEdition]=useState('Original'),[source,setSource]=useState(''),[basis,setBasis]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[bound,setBound]=useState(false),[progress,setProgress]=useState(0);const key=useRef<string|null>(null),lock=useRef(false),abort=useRef<AbortController|null>(null);
 async function call(action:string,extra:object={},signal?:AbortSignal){try{const r=await fetch('/api/drive',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:key.current,...extra}),signal});const data:unknown=await r.json().catch(()=>null);if(!r.ok)throw new DriveError(safeDriveCode(data));signal?.throwIfAborted();return data as {url:string};}catch(e){if(signal?.aborted)throw new DriveError('CANCELLED');throw e instanceof DriveError?e:new DriveError('RETRYABLE');}}
 async function submit(){if(!enabled||!file||lock.current)return;lock.current=true;setBusy(true);setMessage('');abort.current=new AbortController();try{if(file.size>DRIVE_TARGET_BYTES)throw new DriveError('OVERSIZE');key.current??=crypto.randomUUID();setBound(true);await call('begin',{projectId,paperId,filename:file.name,size:file.size,edition,source,accessBasis:basis},abort.current.signal);const session=await call('session',{},abort.current.signal);await uploadDriveChunks(file,session.url,abort.current.signal,n=>setProgress(n));await call('complete',{},abort.current.signal);setDone(true);setMessage('保存済み・未解析。ページ・出典・研究内容は未確認です。');}catch(e){const code=e instanceof DriveError?e.code:'RETRYABLE';setMessage(`${code}: ${driveRecovery(code)} 入力は保持されています。`);}finally{lock.current=false;setBusy(false);}}
 async function newAttempt(){if(lock.current)return;lock.current=true;setBusy(true);try{if(key.current&&!done)await call('cancel');key.current=null;setBound(false);setDone(false);setProgress(0);setMessage('新しい試行です。前の原本・履歴は保持します。');}catch(e){const code=e instanceof DriveError?e.code:'RETRYABLE';setMessage(`${code}: ${driveRecovery(code)} 取消を確認できないため入力を保持しました。`);}finally{lock.current=false;setBusy(false);}}
 return <section className="panel"><h2>Google Drive に原本を保存</h2>{!enabled&&<p role="status">未接続。OAuth・容量・ブラウザー転送の確認が必要です。</p>}<p>希望する上限: {DRIVE_TARGET_BYTES.toLocaleString('en-US')} bytes（100 MB）。実際の保存可能容量は未確認です。別版は新しいファイルとして保存します。</p><form onSubmit={e=>{e.preventDefault();void submit();}}><fieldset disabled={!enabled||busy||done}><label>Drive PDF ファイル<input type="file" accept="application/pdf,.pdf" required disabled={bound} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>Drive 版のラベル<input required value={edition} disabled={bound} onChange={e=>setEdition(e.target.value)}/></label><label>Drive 取得元<input required value={source} disabled={bound} onChange={e=>setSource(e.target.value)}/></label><label>Drive アクセスの根拠<input required value={basis} disabled={bound} onChange={e=>setBasis(e.target.value)}/></label><button type="submit">{busy?'Drive 転送中…':'Drive 保存を開始・再開'}</button></fieldset></form>{busy&&<button onClick={()=>abort.current?.abort()}>転送を中断（再開可能）</button>}<button disabled={!enabled||busy||!bound} onClick={()=>void newAttempt()}>別版・新しい試行</button><progress max={file?.size||1} value={progress} aria-label="Drive 転送バイト数"/><p role="status">{message}</p><p>認証付きの版指定ダウンロードは検証待ちです。インライン表示は利用できません。</p></section>;
}
