'use client';
import {ChemicalStructure,StructureGlyph} from './chemical-structure';
import {useId,useRef,useState} from 'react';
import {reactionNetwork,edgePath,type NetworkNode} from '../domain/reaction-network';
import type {CompoundLink} from '../domain/project-reactions';
import type {BoardRow} from '../domain/whiteboard';
const names:Record<string,string>={oxygen:'酸素あり / 空気',oxygen_free:'明示的な無酸素 / 不活性',unknown:'雰囲気不明'};
function nodeLabel(value:string){let out='',width=0;for(const c of value){width+=c.charCodeAt(0)>255?2:1;if(width>16)return out+'…';out+=c;}return out;}
export function NetworkCanvas({rows,onSelect,links=[],project}:{project?:string;links?:CompoundLink[];rows:BoardRow[];onSelect:(row:string)=>void}){
 const network=reactionNetwork(rows,links),[search,setSearch]=useState(''),[message,setMessage]=useState(''),[view,setView]=useState<{x:number;y:number;k:number}|null>(null),[nodeId,setNodeId]=useState<string|null>(null);const svg=useRef<SVGSVGElement|null>(null),drag=useRef<{x:number;y:number}|null>(null),marker=useId().replaceAll(':','');const [size,setSize]=useState({width:900,height:510});const fit=Math.min((size.width-36)/network.width,(size.height-36)/network.height,1.15),v=view??{x:(size.width-network.width*fit)/2,y:(size.height-network.height*fit)/2,k:fit};
 const measure=(element:SVGSVGElement|null)=>{svg.current=element;if(element){const b=element.getBoundingClientRect();if(b.width!==size.width||b.height!==size.height)setSize({width:b.width,height:b.height});}};
 const selected=network.nodes.find(n=>n.id===nodeId);const selectedRow=rows.find(r=>r.key===selected?.rows[0]),seed=selectedRow?.rows.find(r=>r.version.id===selectedRow.identity.seed_version_id)?.version;const sourceBase=project&&seed?`/projects/${project}/papers/${seed.paper_id}/research`:undefined;function choose(n:NetworkNode){setNodeId(n.id);onSelect(n.rows[0]);if(size.width<600&&n.kind==='compound')setView({k:1,x:size.width/2-(n.x+n.width/2),y:size.height/2-(n.y+n.height/2)});}function searchNode(){const n=network.nodes.find(n=>n.label.toLowerCase().includes(search.toLowerCase()));if(!n){setMessage('現在の表示に一致するノードはありません。');return;}setMessage('');choose(n);setView({k:.9,x:size.width/2-(n.x+n.width/2)*.9,y:size.height/2-(n.y+n.height/2)*.9});}function zoom(factor:number){const k=Math.max(.12,Math.min(3,v.k*factor));setView({k,x:size.width/2-(size.width/2-v.x)*k/v.k,y:size.height/2-(size.height/2-v.y)*k/v.k});}
 return <><div className="board-toolbar"><label>ノード検索<input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')searchNode();}} placeholder="名前で検索（統合はしません）"/></label><button onClick={searchNode}>検索位置へ</button><button aria-label="拡大" onClick={()=>zoom(1.25)}>＋</button><button aria-label="縮小" onClick={()=>zoom(.8)}>−</button><button onClick={()=>setView(null)}>全体を表示</button></div><p role="status">{message}</p><p className="notice">四角は化合物、菱形は反応。矢印は役割に従い参加物を接続します。逆向きの独立した反応も別の根拠を保持します。ドラッグで移動、＋/−で拡大。実線: 支持 / 破線: 提案系 / 赤: 反証・矛盾。名称一致では接続しません。構造を詳しく見るにはノードを選択、または名前で検索してください。</p>
 <svg ref={measure} className="board-canvas" aria-label="移動・拡大できる反応グラフ" onPointerDown={e=>{if((e.target as Element).closest('[data-node]'))return;drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;drag.current={x:e.clientX,y:e.clientY};setView({...v,x:v.x+dx,y:v.y+dy});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
 <defs>{['green','red'].map(color=><marker key={color} id={`${marker}-${color}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill={color==='red'?'#a42c30':'#235c45'}/></marker>)}</defs>
 <g transform={`translate(${v.x} ${v.y}) scale(${v.k})`} data-testid="board-transform">{network.lanes.map(l=><g key={l.id}><rect x={l.x} y={l.y} width={network.width} height={l.height} rx="16" fill={l.id==='oxygen'?'#fff4e7':l.id==='oxygen_free'?'#eff6ee':'#f1f3f5'} stroke="#c1d0c4"/><text x="20" y={l.y+28} fontSize="18" fontWeight="bold">{names[l.id]}</text></g>)}
 {network.edges.map(e=>{const row=rows.find(r=>r.key===e.row)!,a=network.nodes.find(n=>n.id===e.source)!,b=network.nodes.find(n=>n.id===e.target)!,red=e.conflict||e.style==='refuted',path=edgePath(e,network.nodes);return <g key={e.id} data-node="true" data-testid="network-edge" data-source={e.source} data-target={e.target} role="button" tabIndex={0} aria-label={`反応の根拠を開く: ${row.identity.label} · ${names[row.group]} · ${e.role}`} onClick={()=>onSelect(e.row)} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' ')onSelect(e.row);}}><title>{row.identity.label}: {e.role} × {e.coefficient??'?'} · {row.projection.line_style} · {row.identity.definition.claim.scope}</title><path d={path} fill="none" stroke={red?'#a42c30':'#235c45'} strokeWidth="3" strokeDasharray={e.role==='formal_auxiliary'?'2 5':e.style==='solid'?undefined:e.style==='dashed'?'10 6':'3 5'} markerEnd={e.role==='formal_auxiliary'?undefined:`url(#${marker}-${red?'red':'green'})`}/><path d={path} fill="none" stroke="transparent" strokeWidth="20"/><text x={(a.x+a.width+b.x)/2} y={e.backward?Math.min(a.y,b.y)-32:(a.y+a.height/2+b.y+b.height/2)/2-8} fontSize="13" fill="#3a5044">{e.coefficient===null?'× ?':`× ${e.coefficient}`}</text></g>;})}
 {network.nodes.map(n=>{const row=rows.find(r=>r.key===n.rows[0])!,reaction=n.kind==='reaction',highlight=n.id===nodeId||!!search&&n.label.toLowerCase().includes(search.toLowerCase());return <g key={n.id} data-node="true" data-testid={reaction?'reaction-junction':'compound-node'} data-compound-id={n.compound?.id} data-lane={n.lane} role="button" tabIndex={0} aria-label={reaction?`反応: ${n.label} · ${names[n.lane]}`:`ノード: ${n.label} · ${n.compound?.node_type} · ${row.identity.label}`} onClick={()=>choose(n)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')choose(n);}}><title>{n.label}{n.identityConflict?' · 同一 ID の構造属性が矛盾するため別表示':''}</title>{reaction?<path d={`M ${n.x+n.width/2} ${n.y} L ${n.x+n.width} ${n.y+n.height/2} L ${n.x+n.width/2} ${n.y+n.height} L ${n.x} ${n.y+n.height/2} Z`} fill={row.projection.conflict?'#ffe5de':'#235c45'} stroke={highlight?'#b77711':'#235c45'} strokeWidth="3"/>:<rect x={n.x} y={n.y} width={n.width} height={n.height} rx="10" fill={highlight?'#ffedbb':'white'} stroke={n.identityConflict?'#a42c30':highlight?'#ad781f':'#527960'} strokeWidth="2"/>}{reaction?<><text x={n.x+n.width/2} y={n.y+28} textAnchor="middle" fill={row.projection.conflict?'#a42c30':'white'} fontSize="14">{row.projection.conflict?'!':'R'}</text><text x={n.x+22} y={n.y+65} textAnchor="middle" fontSize="12">{n.label.slice(0,25)}</text><text x={n.x+22} y={n.y+82} textAnchor="middle" fontSize="11">{row.identity.definition.claim.scope} · {row.projection.line_style}</text><text x={n.x+22} y={n.y+97} textAnchor="middle" fontSize="10">支持 {row.projection.support_evidence_ids.length} / 反証 {row.projection.refute_evidence_ids.length} / 条件不明 {row.projection.unknown_count}</text></>:<><text x={n.x+10} y={n.y+25} fontSize="15" fontWeight="bold">{nodeLabel(n.label)}</text><text x={n.x+10} y={n.y+45} fontSize="11">{n.compound?.node_type} / {n.compound?.structure_context}</text>{n.compound?.structure?.smiles&&<StructureGlyph compound={n.compound} x={n.x+10} y={n.y+49}/>}<text x={n.x+10} y={n.y+n.height-7} fontSize="10">{n.compound?.structure?.representation==='transition_state'?'TS · ':''}{n.compound?.structure?.smiles?'構造あり · ':'SMILES 未提供 · '}{n.compound?.id.slice(-6)}{n.identityConflict?' · ID 構造矛盾':''}</text></>}</g>;})}</g></svg>
 {selected&&<div className="network-selection"><strong>{selected.label}</strong>{selected.compound&&<ChemicalStructure key={selected.id} compound={selected.compound} sourceBase={sourceBase}/>} {selected.kind==='reaction'&&<><p>反応型: {selectedRow?.identity.definition.reaction.description?.reaction_type??'不明'} · 可逆性: {selectedRow?.identity.definition.reaction.description?.reversibility??'unknown'}</p><p className="preserve-lines">{selectedRow?.identity.definition.reaction.description?.description??'機構記述未提供'}</p><p>出典・帰属: {selectedRow?.identity.definition.reaction.description?.source_anchor_id??'出典未接続'} · {selectedRow?.identity.definition.reaction.description?.attribution??'not_reported'} · 科学的採用は個々の Evidence レビューを確認してください。</p></>}<p>このノードに接続する反応の根拠:</p>{selected.rows.map(key=><button className="secondary" key={key} onClick={()=>onSelect(key)}>{rows.find(r=>r.key===key)!.identity.label}</button>)}</div>}
 </>;
}
