'use client';
import {useRef,useState} from 'react';import Link from 'next/link';
import {boardDefaults,boardRows,invalidBoardRange,type BoardOptions,type BoardRow} from '../domain/whiteboard';
import type {ProjectReviewData} from '../domain/project-reactions';
const groups:Record<string,string>={oxygen:'酸素あり / 空気',oxygen_free:'明示的な無酸素 / 不活性',unknown:'雰囲気不明'};
export function ReactionWhiteboard({project,data}:{project:string;data:ProjectReviewData}){
 const [options,setOptions]=useState<BoardOptions>(boardDefaults),[search,setSearch]=useState(''),[searchMessage,setSearchMessage]=useState(''),[selected,setSelected]=useState<string|null>(null),[view,setView]=useState({x:20,y:20,k:0.8});const drag=useRef<{x:number;y:number}|null>(null);const rows=boardRows(data,options),active=rows.find(r=>r.key===selected);const update=(key:keyof BoardOptions,value:string)=>{setOptions(o=>({...o,[key]:value}));};
 const select=(key:keyof BoardOptions,label:string,choices:[string,string][])=> <label>{label}<select value={options[key]} onChange={e=>update(key,e.target.value)}>{choices.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;
 const num=(key:keyof BoardOptions,label:string)=><label>{label}<input type="number" step="any" value={options[key]} onChange={e=>update(key,e.target.value)}/></label>;
 const zoom=(factor:number)=>setView(v=>({...v,k:Math.max(.25,Math.min(2.5,v.k*factor))}));
 function focusSearch(){setSearchMessage('');const i=rows.findIndex(r=>[r.identity.label,...r.identity.definition.compounds.map(c=>c.name)].some(n=>n.toLowerCase().includes(search.toLowerCase())));if(i>=0){setSelected(rows[i].key);setView({x:15,y:20-i*210*.6,k:.6});}else setSearchMessage('現在の表示に一致するノードはありません。');}
 return <section className="panel whiteboard" aria-label="反応ホワイトボード"><h2>プロジェクト全体の反応</h2><p>条件を同じ実験の根拠に適用してから集約します。酸素群は別々に表示。実線も表示された主張範囲だけの支持で、正味変換から素反応機構を証明しません。</p>
 <details className="board-filters"><summary>基質・濃度・温度・根拠を絞り込む</summary><div className="board-filter-grid">
 {select('substrate','基質（実験の明示的な分類）',[['','すべて / 混合を保持'],['glucose','グルコースを含む'],['cellulose','セルロースを含む']])}
 {select('alkali','添加アルカリ（完全な添加物リスト）',[['','すべて'],['NaOH','NaOH のみ'],['KOH','KOH のみ'],['none','添加なし（明示）']])}
 {select('aqueous','水系',[['','すべて'],['water','水を含む（明示）'],['non_aqueous','非水系（明示）']])}
 {num('concentrationMin','NaOH 濃度下限')}{num('concentrationMax','NaOH 濃度上限')}
 {select('concentrationUnit','NaOH 濃度の単位',[['mol/L','mol/L'],['mol/kg','mol/kg'],['wt%','wt%'],['g/L','g/L']])}
 {select('concentrationBasis','NaOH 濃度の基準',[['solution_volume','溶液体積'],['solvent_mass','溶媒質量'],['solution_mass','溶液質量'],['dry_substrate_mass','乾燥基質質量']])}
 {num('temperatureMin','温度下限（reaction_medium / degC）')}{num('temperatureMax','根拠の温度上限（reaction_medium / degC）')}
 {select('stage','根拠の条件段階',[['reaction','reaction'],['pretreatment','pretreatment'],['workup','workup'],['analysis','analysis']])}
 {select('atmosphere','雰囲気 / 酸素群',[['','各群を別々に表示'],['oxygen',groups.oxygen],['oxygen_free',groups.oxygen_free],['unknown',groups.unknown]])}
 {select('catalyst','添加触媒',[['','すべて'],['none','添加触媒なし（明示・完全リスト）'],...Array.from(new Set(data.versions.flatMap(v=>v.payload.experiment.conditions.filter(c=>c.key==='added_catalyst'&&c.value_state==='reported').flatMap(c=>c.terms)))).filter(t=>t!=='none').sort().map(t=>[t,t+' のみ（明示・完全リスト）'] as [string,string])])}
 {select('evidenceClass','根拠分類',[['','すべて'],...['directly_observed','strongly_supported','proposed','adopted_from_prior_literature','speculative'].map(x=>[x,x] as [string,string])])}
 {select('review','人による科学レビュー',[['accepted','採用された改訂'],['all','すべて（未採用は接続なし）'],['pending','未採用のみ（接続なし）']])}
 </div><p>指定範囲に報告範囲全体が収まる場合だけ一致します。単位・基準は完全一致で換算せず、不明・未報告・重複は条件不明として残します。pH を濃度に換算しません。名称で基質を推測・統合しません。</p><button className="secondary" onClick={()=>setOptions(boardDefaults)}>条件をリセット</button></details>
 {invalidBoardRange(options)&&<p role="alert">数値範囲を確認してください。下限は上限以下、濃度は非負で指定してください。</p>}
 <div className="board-toolbar"><label>ノード検索<input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')focusSearch();}} placeholder="名前で検索（統合はしません）"/></label><button onClick={focusSearch}>検索位置へ</button><button aria-label="拡大" onClick={()=>zoom(1.25)}>＋</button><button aria-label="縮小" onClick={()=>zoom(.8)}>−</button><button onClick={()=>setView({x:20,y:20,k:.8})}>表示を戻す</button></div>
 <p role="status">{searchMessage}</p><p className="notice">ドラッグで移動、＋/−で拡大縮小。ノード・反応線を押すと下の出典パネルを開きます。実線: 範囲内の強い支持 / 破線: 提案系 / 赤点線: 反証 / 接続なし: 未採用・条件不明・除外。</p>
 <svg className="board-canvas" aria-label="移動・拡大できる反応グラフ" onPointerDown={e=>{if((e.target as Element).closest('[data-node]'))return;drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;drag.current={x:e.clientX,y:e.clientY};setView(v=>({...v,x:v.x+dx,y:v.y+dy}));}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
 <g transform={`translate(${view.x} ${view.y}) scale(${view.k})`} data-testid="board-transform">{rows.map((r,i)=>{const p=r.identity.definition,linked=['solid','dashed','refuted'].includes(r.projection.line_style),color=r.projection.conflict?'#a42c30':'#235c45';return <g key={r.key} transform={`translate(0 ${i*210})`}><rect width="1080" height="195" rx="12" fill={r.group==='oxygen'?'#fff3e8':r.group==='oxygen_free'?'#edf5ef':'#f0f1f3'} stroke="#c4cfc8"/><text x="16" y="25" fontSize="16">{groups[r.group]} · {r.identity.label.slice(0,45)} · {r.projection.line_style}{r.projection.conflict?' · 矛盾あり':''}</text>{p.reaction.participants.map((part,j)=>{const c=p.compounds.find(c=>c.id===part.compound_id)!;const x=16+j*130,highlight=!!search&&c.name.toLowerCase().includes(search.toLowerCase());return <g key={`${r.key}:${c.id}:${j}`} data-node="true" role="button" tabIndex={0} aria-label={`ノード: ${c.name} · ${c.node_type} · ${r.identity.label}`} onClick={()=>setSelected(r.key)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')setSelected(r.key);}}><rect x={x} y="50" width="120" height="66" rx="8" fill={highlight?'#ffe2a5':'white'} stroke={highlight?'#a66c00':'#718a7b'}/><text x={x+8} y="73" fontSize="13">{c.name.slice(0,14)}</text><text x={x+8} y="92" fontSize="11">{part.role} × {part.coefficient??'?'}</text><text x={x+8} y="108" fontSize="10">{c.node_type}</text></g>;})}{linked?<g data-node="true" role="button" tabIndex={0} aria-label={`反応の根拠を開く: ${r.identity.label} · ${groups[r.group]}`} onClick={()=>setSelected(r.key)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')setSelected(r.key);}}><path d="M 22 145 H 1000 l -12 -7 m 12 7 l -12 7" fill="none" stroke={color} strokeWidth="4" strokeDasharray={r.projection.line_style==='solid'?undefined:r.projection.line_style==='dashed'?'10 7':'3 6'}/><path d="M 22 145 H 1000" stroke="transparent" strokeWidth="30"/><text x="22" y="180" fontSize="14">{p.claim.scope} · 支持 {r.projection.support_evidence_ids.length} / 反証 {r.projection.refute_evidence_ids.length} / 不明 {r.projection.unknown_count}</text></g>:<text x="22" y="156" fontSize="14">接続なし · 条件不明 {r.projection.unknown_count} / 条件除外 {r.projection.excluded_count} · ノードから履歴を確認</text>}</g>;})}</g></svg>
 {!rows.length&&<p>この表示条件に該当する記録はありません。</p>}
 {active&&<SourcePanel project={project} data={data} row={active}/>}
 <details><summary>グラフの根拠一覧（キーボード・詳細表示）</summary>{rows.map(r=><article key={r.key} id={`reaction-${r.identity.id}`}><h3>{r.identity.label} · {groups[r.group]}</h3><p>表示: {r.projection.line_style} · 支持 {r.projection.support_evidence_ids.length} · 反証 {r.projection.refute_evidence_ids.length} · 条件不明 {r.projection.unknown_count} · 条件除外 {r.projection.excluded_count}</p><button onClick={()=>setSelected(r.key)}>出典パネルを開く: {r.identity.label}</button></article>)}</details>
 </section>;
}
function SourcePanel({project,data,row:r}:{project:string;data:ProjectReviewData;row:BoardRow}){return <section className="board-source" aria-label="選択した反応と出典"><h3>{r.identity.label} · {groups[r.group]}</h3><p>主張範囲: {r.identity.definition.claim.scope} · {r.identity.definition.claim.proposition}</p>{r.projection.conflict&&<p role="status">矛盾あり: 同条件の支持と反証を保持しています。</p>}<p>確認された独立性グループ: {r.projection.confirmed_independent_groups}{r.projection.independence_unknown?' · 未解決の独立性あり':''}</p>{r.rows.map(({version:v,reason})=>{const a=data.anchors.find(a=>a.id===v.payload.evidence.source_anchor_id),att=data.attestations.filter(x=>x.anchor_id===a?.id).sort((a,b)=>b.revision-a.revision)[0];return <article key={v.id}><h4>{v.payload.evidence.evidence_type} · {v.payload.evidence.stance} · 改訂 {v.revision}</h4><p>{reason} · この条件: {r.projection.support_evidence_ids.includes(v.id)?'支持':r.projection.refute_evidence_ids.includes(v.id)?'反証':r.projection.unknown_evidence_ids.includes(v.id)?'不明':'未採用・除外'}</p><p>元実験: {v.payload.experiment.original_experiment_id??'不明'} · 独立性: {v.payload.experiment.independence_group_id??'不明'}</p><ul>{v.payload.compounds.map(c=><li key={c.id}>{c.name} · {c.node_type} / {c.structure_context} · ID {c.id}</li>)}</ul><ul>{v.payload.experiment.conditions.map((c,i)=><li key={i}>{c.key}: {c.value_state} · {c.kind==='interval'?`${c.lower_inclusive?'[':'('}${c.lower??'?'}, ${c.upper??'?'}${c.upper_inclusive?']':')'}`:c.terms.join(', ')} {c.unit} · 基準 {c.basis} · {v.payload.experiment.stage} · 原文 {c.raw_value_text}</li>)}</ul>{a&&<><p>物理ページ {a.physical_page_start??'?'}–{a.physical_page_end??'?'} · 印刷表記 {a.printed_page_label??'不明'}</p><blockquote className="preserve-lines">{a.verbatim_passage??'原文は出典ページで確認してください。'}</blockquote><p>原本レシート: {att?.receipt_id??'未照合'} · 保存済み PDF SHA-256: {att?.receipt_sha256??'未照合'} · 引用文 SHA-256: {a.passage_hash}</p><p>人の照合: {att?.decision??'未照合'} · {att?.created_by} · {att?.created_at}。自動 PDF 検証ではありません。</p></>}<Link href={`/projects/${project}/papers/${v.paper_id}/research/${v.case_id}`}>根拠を編集・改訂履歴を見る</Link><p><Link href={`/projects/${project}/papers/${v.paper_id}/research#source-${a?.id??''}`}>原文・PDF の版・人の出典照合</Link></p></article>;})}</section>;}
