'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import type {ResearchCase} from '../domain/research-case';
import type {ImportPreview} from '../server/research-cases';
const labels:Record<string,string>={compounds:'化合物',reaction:'反応',claim:'主張',experiment:'実験・条件',evidence:'根拠',name:'名前',aliases:'別名（1 行に 1 件）',node_type:'対象の種類',structure_context:'遊離・結合の区別',stereochemistry:'立体化学（空欄は不明）',protonation:'プロトン化状態（空欄は不明）',formula:'分子式（空欄は不明）',charge:'電荷（空欄は不明）',epistemic_status:'構造の確かさ',representation_scope:'反応の表現範囲',equation_balance_status:'収支の確認',product_inventory_status:'生成物一覧の完全性',participants:'反応参加物',compound_id:'化合物 ID',role:'役割',coefficient:'係数（空欄は不明）',primary_for_display:'図で主として表示',scope:'主張の範囲',proposition:'主張の文章',asserted_by:'主張者',original_experiment_id:'元の実験識別子（空欄は未解決）',independence_group_id:'独立性グループ（空欄は未解決）',origin_resolution_status:'元実験の解決状態',stage:'条件が属する段階',conditions:'条件',key:'条件名',dimension:'物理量',basis:'基準',unit:'比較用の単位',value_state:'値の報告状態',kind:'値の形式',lower:'下限（空欄は不明）',upper:'上限（空欄は不明）',lower_inclusive:'下限を含む',upper_inclusive:'上限を含む',terms:'項目（1 行に 1 件）',inventory_complete:'全項目が記載されている',raw_value_text:'原文の値',raw_unit:'原文の単位',derivation:'値の由来',calculation:'計算の根拠',stance:'支持・反証',evidence_type:'根拠分類',measured_scope:'実際に観測した範囲',epistemic_origin:'著者と分析者の区別',source_access:'出典へのアクセス',strength_rationale:'判断理由',alternatives_tested:'比較した代替説明（1 行に 1 件）',limitations:'限界（1 行に 1 件）',source_anchor_id:'出典アンカー ID（未確認なら空欄）'};
const scope=['product_presence','net_conversion','intermediate_presence','elementary_mechanism','pathway','order_of_steps'];
const choices:Record<string,string[]>={node_type:['discrete_molecule','intermediate','polymer','polymer_site','mixture','class'],structure_context:['free','bound','polymer_site','unknown'],epistemic_status:['observed','hypothetical','unspecified'],representation_scope:['net_conversion','elementary_step','pathway_segment'],equation_balance_status:['checked','unchecked','not_applicable','unknown'],product_inventory_status:['complete','partial','unknown'],role:['reactant','product','formal_auxiliary'],scope,measured_scope:['',...scope],asserted_by:['authors','analyst'],origin_resolution_status:['unresolved','confirmed'],stage:['reaction','pretreatment','workup','analysis'],value_state:['unknown','reported','not_reported','not_applicable','ambiguous'],kind:['interval','controlled_term','composition'],derivation:['reported','calculated'],stance:['supports','refutes','inconclusive'],evidence_type:['directly_observed','strongly_supported','proposed','adopted_from_prior_literature','speculative'],epistemic_origin:['experiment_report','authors_interpretation','cited_interpretation','analyst_inference'],source_access:['unavailable','fulltext','abstract_only','secondary_only']};
const nullable=new Set(['stereochemistry','protonation','formula','charge','coefficient','original_experiment_id','independence_group_id','lower','upper','calculation','measured_scope','source_anchor_id']);const numeric=new Set(['charge','coefficient','lower','upper']);
function Fields({name,value,onChange}:{name:string;value:unknown;onChange:(v:unknown)=>void}){
 if(name==='id')return <small style={{overflowWrap:'anywhere'}}>ID: {String(value)}</small>;
 if(Array.isArray(value)){
  if(['aliases','terms','alternatives_tested','limitations'].includes(name))return <label>{labels[name]}<textarea value={value.join('\n')} onChange={e=>onChange(e.target.value.split('\n'))}/></label>;
  return <fieldset><legend>{labels[name]}</legend>{value.map((item,i)=><section className="panel" key={i}><Fields name={`${name} ${i+1}`} value={item} onChange={v=>onChange(value.map((x,j)=>j===i?v:x))}/><button type="button" onClick={()=>onChange(value.filter((_,j)=>j!==i))}>この項目を除く</button></section>)}<button type="button" onClick={()=>{const id=crypto.randomUUID();const entry=name==='compounds'?{id,name:'',aliases:[],node_type:'discrete_molecule',structure_context:'unknown',stereochemistry:null,protonation:null,formula:null,charge:null,epistemic_status:'unspecified'}:name==='participants'?{compound_id:'',role:'product',coefficient:null,primary_for_display:false}:{key:'',dimension:'',basis:'',unit:'',value_state:'unknown',kind:'interval',lower:null,upper:null,lower_inclusive:true,upper_inclusive:true,terms:[],inventory_complete:false,raw_value_text:'',raw_unit:'',derivation:'reported',calculation:null};onChange([...value,entry]);}}>{labels[name]}を追加</button></fieldset>;
 }
 if(value!==null&&typeof value==='object')return <fieldset><legend>{labels[name]??name}</legend>{Object.entries(value).map(([k,v])=><Fields key={k} name={k} value={v} onChange={next=>onChange({...value,[k]:next})}/>)}</fieldset>;
 if(typeof value==='boolean')return <label><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{labels[name]}</label>;
 if(choices[name])return <label>{labels[name]}<select value={String(value??'')} onChange={e=>onChange(e.target.value===''&&nullable.has(name)?null:e.target.value)}>{choices[name].map(c=><option key={c} value={c}>{c||'不明 / 未指定'}</option>)}</select></label>;
 return <label>{labels[name]??name}<input type={numeric.has(name)?'number':'text'} step="any" value={value===null?'':String(value)} onChange={e=>onChange(e.target.value===''&&nullable.has(name)?null:numeric.has(name)?Number(e.target.value):e.target.value)}/></label>;
}
export function ResearchCaseEditor({project,paper,id,revision,initial,archived=false}:{project:string;paper:string;id:string;revision:number;initial:ResearchCase;archived?:boolean}){
 const [payload,setPayload]=useState(initial),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);const router=useRouter();
 async function act(action:string){if(lock.current)return;lock.current=true;setBusy(true);try{const r=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,project,paper,id,revision,...(action==='save'?{payload:JSON.parse(JSON.stringify(payload,(key,value)=>['aliases','terms','alternatives_tested','limitations'].includes(key)&&Array.isArray(value)?value.filter(x=>typeof x==='string'&&x.trim().length>0):value))}:{}),...(action==='archive'?{archived:!archived}:{reason})})});const result=await r.json();if(!r.ok)throw Error(result.error);setMessage('履歴を残して保存しました。出典未確認の内容は下書きのままです。');router.push(`/projects/${project}/papers/${paper}/research/${id}`);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'保存できません。入力は保持しています。');}finally{lock.current=false;setBusy(false);}}
 return <section className="panel science-fields"><h2>{revision?'研究内容を改訂':'研究ケースを作成'}</h2><p>化合物 ID は同名でも統合しません。元の値と単位を保持してください。出典・ページの確認機能は未接続のため、支持された事実として図に表示しません。</p><form onSubmit={e=>{e.preventDefault();void act('save');}}><fieldset disabled={busy||archived}>{Object.entries(payload).map(([k,v])=><details key={k} open={k==='claim'||k==='evidence'}><summary>{labels[k]}</summary><Fields name={k} value={v} onChange={next=>setPayload({...payload,[k]:next})}/></details>)}<label>変更・確認の理由<input required value={reason} maxLength={4000} onChange={e=>setReason(e.target.value)}/></label><button type="submit">{busy?'保存中…':'下書きとして保存'}</button>{revision>0&&<button type="button" disabled={!reason||JSON.stringify(payload)!==JSON.stringify(initial)} onClick={()=>void act('review')}>保存済み内容を人が確認（出典未確認）</button>}</fieldset></form>{revision>0&&<button disabled={busy} onClick={()=>void act('archive')}>{archived?'復元':'アーカイブ'}</button>}<p role="status" aria-live="polite">{message}</p></section>;
}
export function ResearchImport({project,paper}:{project:string;paper:string}){const [raw,setRaw]=useState(''),[preview,setPreview]=useState<ImportPreview|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const key=useRef<string|null>(null),lock=useRef(false);const router=useRouter();async function run(apply=false){if(lock.current)return;lock.current=true;setBusy(true);try{key.current??=crypto.randomUUID();const r=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:apply?'apply':'stage',project,paper,id:apply?preview!.id:key.current,...(!apply?{raw}:{})})});const result=await r.json();if(!r.ok)throw Error(result.error);if(apply){setMessage('AI 下書きとして適用しました。人の確認にはなりません。');router.refresh();}else{setPreview(result);setMessage('差分を確認してください。まだ研究データへ適用していません。');}}catch(e){setMessage(e instanceof Error?e.message:'検証できません。');}finally{lock.current=false;setBusy(false);}}return <section className="panel"><h2>研究 JSON の取り込み</h2><p>research-case/0.1 · 128 KiB 以下。AI は確認者・確認済み状態を指定できません。</p><label>JSON<textarea value={raw} onChange={e=>{setRaw(e.target.value);setPreview(null);key.current=null;}} rows={10} disabled={busy}/></label><button disabled={busy||!raw} onClick={()=>void run()}>検証して差分を表示</button>{preview&&<><p>{preview.stale?'元の改訂番号と現在の内容が異なります。JSON を再確認してください。':preview.humanProtected?'人の編集・確認があるため自動上書きできません。内容を比較し、必要な変更を手動で反映してください。':'適用すると、単一の処理で AI 下書きと履歴を保存します。'}</p>{preview.diff.map(d=><details key={d.section}><summary>{labels[d.section]}の差分</summary><h3>現在</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(d.before,null,2)}</pre><h3>取り込み案</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(d.after,null,2)}</pre></details>)}<button disabled={busy||preview.humanProtected||preview.stale} onClick={()=>void run(true)}>この下書き案を適用</button></>}<p role="status">{message}</p></section>;}
