// Disposable PostgreSQL only; a real max=2 pg pool catches nested-acquisition deadlocks.
import {Pool} from 'pg';import assert from 'node:assert/strict';
import {PostgresSecretVault} from '../src/server/drive/vault';import {DriveOAuth,encryptedSessions} from '../src/server/drive/oauth-service';import {GoogleDriveAdapter} from '../src/server/drive/adapter';import {DriveService,type DriveRepository} from '../src/server/drive/service';import {type DriveIntent} from '../src/application/drive';
async function main(){
const port=Number(process.argv[2]);assert.ok(Number.isInteger(port)&&port>0&&port<65536);const pool=new Pool({host:'127.0.0.1',port,user:'kg_pool_test',database:'postgres',max:2,connectionTimeoutMillis:3000,ssl:false});
const user='11111111-1111-4111-8111-111111111111',binding='22222222-2222-4222-8222-222222222222';const vault=new PostgresSecretVault(pool,async()=>({id:user}),'SYNTHETIC','kg_pool_test',Buffer.alloc(32,17));let created=0;
try{await vault.transaction('token:'+binding,async t=>t.put({accessToken:'SYNTHETIC-access',refreshToken:'SYNTHETIC-refresh',expiresAt:Date.now()+3600000,accountId:'SYNTHETIC-account'},Date.now()+3600000));
 const http:typeof fetch=async(input,init)=>{const u=String(input);assert.equal(new Headers(init?.headers).get('authorization'),'Bearer SYNTHETIC-access');if(u.includes('/about?'))return Response.json({user:{permissionId:'SYNTHETIC-account'}});if(u.includes('/files/SYNTHETIC-folder?'))return Response.json({id:'SYNTHETIC-folder',mimeType:'application/vnd.google-apps.folder',ownedByMe:true,shared:false,appProperties:{kgFolder:'originals'}});const session=++created;await new Promise(r=>setTimeout(r,30));return new Response(null,{headers:{location:'https://www.googleapis.com/upload/drive/v3/files?upload_id=SYNTHETIC-'+session}});};
 const tokens=new DriveOAuth({clientId:'SYNTHETIC',clientSecret:'SYNTHETIC',redirectUri:'https://synthetic.example/api/drive/oauth/callback'},user,vault,{async project(){throw Error();},async bind(){throw Error();}},http);
 const repo={async authorize(){},async findIntent(id:string){return {id,projectId:user,paperId:user,binding:{id:binding,accountId:'SYNTHETIC-account',folderId:'SYNTHETIC-folder'},fileId:'SYNTHETIC-file-'+id,filename:'SYNTHETIC.pdf',size:9,edition:'SYNTHETIC',source:'SYNTHETIC',accessBasis:'SYNTHETIC',expiresAt:Date.now()+3600000,cancelled:false} satisfies DriveIntent;},async receipt(){return null;}} as unknown as DriveRepository;
 const service=new DriveService(repo,new GoogleDriveAdapter(tokens,http),encryptedSessions(vault));const a='33333333-3333-4333-8333-333333333333',b='44444444-4444-4444-8444-444444444444';const result=await Promise.all([service.uploadSession(a),service.uploadSession(b),service.uploadSession(a)]);assert.equal(created,2);assert.equal(result[0].url,result[2].url);assert.notEqual(result[0].url,result[1].url);assert.ok(pool.totalCount<=2);console.log('PASS: real max=2 pool creates concurrent sessions without nested-acquisition deadlock; same intent replays once');
}finally{await pool.end();}

}
void main().catch(e=>{console.error("FAIL: real-pool concurrent session regression",e instanceof Error?e.name+": "+e.message:"unknown");process.exitCode=1;});
