import test from 'node:test';
import assert from 'node:assert/strict';
import {ResearchDAL,type ResearchGateway} from '../../src/server/research';
import {AppError,createPaperInput} from '../../src/application/models';
import {supabaseConfig} from '../../src/server/supabase/config';
const owner='11111111-1111-4111-8111-111111111111',project='22222222-2222-4222-8222-222222222222',paper='33333333-3333-4333-8333-333333333333',request='44444444-4444-4444-8444-444444444444';
function fixture(){
 let authenticated=true,owns=true;const writes:{operation:string;args:Record<string,unknown>}[]=[];let verifications=0;const reads:string[]=[];
 const gateway:ResearchGateway={verifiedUser:async()=>{verifications++;return authenticated?{id:owner}:null;},ownsProject:async(id,user)=>{reads.push(`scope:${id}:${user}`);return owns&&id===project;},listProjects:async()=>[],getProject:async()=>({id:project,name:'SYNTHETIC',description:'',revision:1,archived_at:null}),listPapers:async()=>[],getPaper:async(pid,id)=>pid===project&&id===paper?({id:paper,project_id:project,title:'SYNTHETIC',journal:null,year:null,notes:null,revision:1,archived_at:null,doi:null}):null,write:async(operation,args)=>{writes.push({operation,args});return paper;}};
 return {dal:new ResearchDAL(gateway),writes,reads,checks:()=>verifications,unauth:()=>{authenticated=false;},forbid:()=>{owns=false;}};
}
const create={project_id:project,request_id:request,title:'SYNTHETIC title',journal:'',year:'2026',notes:'',doi:'https://doi.org/10.1234/SYNTHETIC'};
const rejects=(code:string)=>(error:unknown)=>error instanceof AppError&&error.code===code;
test('every DAL read verifies authentication and project-scoped reads verify ownership',async()=>{const f=fixture();await f.dal.projects();await f.dal.project(project);await f.dal.papers(project);await f.dal.paper(project,paper);assert.equal(f.checks(),4);assert.equal(f.reads.length,3);});
test('unverified session cannot list or create data',async()=>{const f=fixture();f.unauth();await assert.rejects(f.dal.projects(),rejects('UNAUTHENTICATED'));await assert.rejects(f.dal.createPaper(create),rejects('UNAUTHENTICATED'));await assert.rejects(f.dal.createProject({name:'SYNTHETIC',description:'',request_id:request}),rejects('UNAUTHENTICATED'));assert.equal(f.writes.length,0);});
test('cross-project read, create, edit and archive all fail before gateway write',async()=>{const f=fixture();f.forbid();await assert.rejects(f.dal.paper(project,paper),rejects('FORBIDDEN'));await assert.rejects(f.dal.createPaper(create),rejects('FORBIDDEN'));await assert.rejects(f.dal.editPaper({project_id:project,paper_id:paper,revision:1,title:'SYNTHETIC',journal:'',year:'',notes:''}),rejects('FORBIDDEN'));await assert.rejects(f.dal.archive({project_id:project,revision:1,archived:'true'}),rejects('FORBIDDEN'));assert.equal(f.writes.length,0);});
test('paper ID from another project cannot be returned',async()=>{const f=fixture();await assert.rejects(f.dal.paper(project,request),rejects('FORBIDDEN'));});
test('create validates DOI and carries request ID, never actor or review fields',async()=>{const f=fixture();await f.dal.createPaper(create);assert.equal(f.writes[0].args.p_doi,'10.1234/synthetic');assert.equal(f.writes[0].args.p_request_id,request);assert.equal(f.writes[0].args.p_year,2026);assert.ok(!('created_by' in f.writes[0].args));});
for(const [field,value] of [['title','   '],['title','x'.repeat(501)],['year','0999'],['year','9999'],['year','2026.1'],['doi','not-a-doi'],['doi','10.1234/has space']])test(`invalid ${field}: server rejects without writing`,async()=>{const f=fixture();await assert.rejects(f.dal.createPaper({...create,[field]:value}),rejects('INVALID'));assert.equal(f.writes.length,0);});
test('unknown publication/review/actor metadata is rejected rather than passed through',async()=>{const f=fixture();for(const key of ['created_by','owner_user_id','review_state','publication_status'])await assert.rejects(f.dal.createPaper({...create,[key]:'forged'}),rejects('INVALID'));assert.equal(f.writes.length,0);});
test('stale-edit revision reaches atomic DB RPC; gateway conflict is retained',async()=>{const f=fixture();await f.dal.editPaper({project_id:project,paper_id:paper,revision:7,title:'SYNTHETIC',journal:'',year:'',notes:''});assert.equal(f.writes[0].args.p_revision,7);assert.equal(f.writes[0].args.p_project_id,project);});
test('archive and restore use expected revision and no delete operation',async()=>{const f=fixture();await f.dal.archive({project_id:project,paper_id:paper,revision:1,archived:'true'});await f.dal.archive({project_id:project,paper_id:paper,revision:2,archived:'false'});assert.equal(f.writes[0].operation,'archive_paper');assert.equal(f.writes[1].args.p_archived,false);});
test('project create/edit input rejects spoofed owner and revision zero',async()=>{const f=fixture();await assert.rejects(f.dal.createProject({request_id:request,name:'SYNTHETIC',description:'',owner_user_id:owner}),rejects('INVALID'));await assert.rejects(f.dal.editProject({project_id:project,name:'SYNTHETIC',description:'',revision:0}),rejects('INVALID'));});
test('unknown year stays null and DOI URL normalization is explicit',()=>{assert.equal(createPaperInput.parse({...create,year:''}).year,null);assert.equal(createPaperInput.parse({...create,doi:' DOI:10.1234/Synthetic '}).doi,'10.1234/synthetic');});
test('configuration fails closed for absent settings and secret-shaped keys',()=>{
 const previousUrl=process.env.NEXT_PUBLIC_SUPABASE_URL,previousKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
 try{delete process.env.NEXT_PUBLIC_SUPABASE_URL;delete process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;assert.equal(supabaseConfig(),null);process.env.NEXT_PUBLIC_SUPABASE_URL='https://synthetic.invalid';process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY='sb_secret_SYNTHETIC_NOT_A_KEY';assert.equal(supabaseConfig(),null);process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY='sb_publishable_SYNTHETIC_NOT_A_KEY';assert.ok(supabaseConfig());process.env.NEXT_PUBLIC_SUPABASE_URL='javascript:synthetic';assert.equal(supabaseConfig(),null);}finally{if(previousUrl===undefined)delete process.env.NEXT_PUBLIC_SUPABASE_URL;else process.env.NEXT_PUBLIC_SUPABASE_URL=previousUrl;if(previousKey===undefined)delete process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;else process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=previousKey;}
});
