import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {DriveOAuth,encryptedSessions} from '../../src/server/drive/oauth-service';import {GoogleDriveAdapter} from '../../src/server/drive/adapter';import {DriveService,type DriveRepository} from '../../src/server/drive/service';import type {SecretVault} from '../../src/server/drive/vault';import {uploadDriveChunks} from '../../src/application/drive-upload';import {DRIVE_SCOPE,type DriveBinding,type DriveIntent,type DriveReceipt} from '../../src/application/drive';
test('connected synthetic OAuth → direct chunk upload → receipt → reload reconciliation',async()=>{
 const user='11111111-1111-4111-8111-111111111111',project='22222222-2222-4222-8222-222222222222',paper='33333333-3333-4333-8333-333333333333',id='44444444-4444-4444-8444-444444444444';const bytes=Buffer.concat([Buffer.from('%PDF-1.7\nSYNTHETIC fixture\n'),Buffer.alloc(300000,32)]);let binding:DriveBinding|null=null,intent:DriveIntent|null=null,receipt:DriveReceipt|null=null,uploaded=Buffer.alloc(0),sessions=0,refresh=0;const stored=new Map<string,unknown>();
 const vault:SecretVault={async transaction(key,fn){return fn({value:stored.get(key)??null,put(v){stored.set(key,v);},remove(){stored.delete(key);}});}};
 const http:typeof fetch=async(url,init={})=>{const u=new URL(String(url));if(u.hostname==='oauth2.googleapis.com'){const body=init.body as URLSearchParams;if(body.get('grant_type')==='refresh_token')refresh++;return Response.json({access_token:'SYNTHETIC-access',refresh_token:'SYNTHETIC-refresh',expires_in:refresh?3600:1,scope:DRIVE_SCOPE});}
  if(u.searchParams.has('upload_id')){assert.equal(init.credentials,'omit');assert.equal(init.redirect,'error');assert.equal(init.referrerPolicy,'no-referrer');assert.equal(new Headers(init.headers).has('authorization'),false);if(init.body)uploaded=Buffer.concat([uploaded,Buffer.from(await (init.body as Blob).arrayBuffer())]);return uploaded.length===bytes.length?Response.json({id:'SYNTHETIC-file'}):new Response(null,{status:308,headers:uploaded.length?{Range:`bytes=0-${uploaded.length-1}`}:{}});}
  assert.equal(new Headers(init.headers).get('authorization'),'Bearer SYNTHETIC-access');
  if(u.pathname.endsWith('/about'))return Response.json({user:{permissionId:'SYNTHETIC-account'},storageQuota:{limit:'100000000',usage:'0'},maxUploadSize:'100000000'});
  if(u.pathname.endsWith('/files/generateIds'))return Response.json({ids:['SYNTHETIC-file']});
  if(u.pathname==='/upload/drive/v3/files'){sessions++;assert.equal(u.searchParams.get('keepRevisionForever'),'true');return new Response(null,{status:200,headers:{Location:'https://www.googleapis.com/upload/drive/v3/files?upload_id=SYNTHETIC'}});}
  if(u.pathname.endsWith('/files')&&init.method==='POST')return Response.json({id:'SYNTHETIC-folder'});
  if(u.pathname.endsWith('/files/SYNTHETIC-folder'))return Response.json({id:'SYNTHETIC-folder',mimeType:'application/vnd.google-apps.folder',ownedByMe:true,shared:false,appProperties:{kgFolder:'originals'}});
  if(u.pathname.includes('/revisions/')){assert.equal(u.pathname.split('/').at(-1),'SYNTHETIC-r1');return new Response(uploaded);}
  if(u.pathname.endsWith('/files/SYNTHETIC-file'))return Response.json({id:'SYNTHETIC-file',headRevisionId:'SYNTHETIC-r1',size:uploaded.length,mimeType:'application/pdf',ownedByMe:true,shared:false,parents:['SYNTHETIC-folder'],appProperties:{kgIntent:id}});
  throw Error('Unexpected synthetic transport request');
 };
 const oauth=()=>new DriveOAuth({clientId:'SYNTHETIC-client',clientSecret:'SYNTHETIC-secret',redirectUri:'https://synthetic.example/api/drive/oauth/callback'},user,vault,{async project(p){assert.equal(p,project);return binding;},async bind(b,p,a,f){assert.equal(p,project);binding={id:b,accountId:a,folderId:f};}},http);
 const auth=oauth(),url=new URL(await auth.start(project));await auth.callback(url.searchParams.get('state')!,'SYNTHETIC-code');
 const repo:DriveRepository={async authorize(p,d){assert.equal(p,project);assert.equal(d,paper);},async binding(){assert.ok(binding);return binding;},async findIntent(){return intent;},async begin(input,b,fileId){intent={...input,binding:b,fileId,expiresAt:Date.now()+3600000,cancelled:false};return intent;},async receipt(){return receipt;},async finalize(i,v){receipt={id:'55555555-5555-4555-8555-555555555555',intentId:i.id,projectId:project,paperId:paper,provider:'google_drive',fileId:i.fileId,...v,state:'stored_unparsed'};return receipt;},async event(){},async cancel(){if(intent)intent.cancelled=true;},async list(){return intent?[intent]:[];}};
 const service=()=>new DriveService(repo,new GoogleDriveAdapter(oauth(),http),encryptedSessions(vault));const s=service();await s.begin({id,projectId:project,paperId:paper,filename:'SYNTHETIC.pdf',size:bytes.length,edition:'Original',source:'SYNTHETIC',accessBasis:'synthetic fixture'});const session=await s.uploadSession(id);await uploadDriveChunks(new Blob([bytes]),session.url,new AbortController().signal,()=>{},http);
 // New service objects model reload after direct upload, before the completion response.
 const recovered=service();assert.equal((await recovered.status(id)).receipt,null);assert.equal((await recovered.uploadSession(id)).url,session.url);const saved=await recovered.complete(id);assert.equal(saved.sha256,createHash('sha256').update(bytes).digest('hex'));assert.equal(saved.state,'stored_unparsed');assert.equal((await service().attempts(project,paper))[0].receipt?.id,saved.id);assert.equal((await service().complete(id)).id,saved.id);assert.equal(sessions,1);assert.equal(refresh,1);assert.equal((await service().checkDownload(id)).receipt.revisionId,'SYNTHETIC-r1');const viewer=await service().viewer(id);assert.equal(viewer.mode,'mutable_drive_viewer');assert.equal(viewer.url,'https://drive.google.com/file/d/SYNTHETIC-file/view');uploaded=Buffer.from('CHANGED');await assert.rejects(service().viewer(id),/REPLACED/);
});
