import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {DriveService,type DriveRepository,type SessionVault} from '../../src/server/drive/service';
import {GoogleDriveAdapter,type DriveAdapter,assertSessionURL} from '../../src/server/drive/adapter';
import {DriveError,DRIVE_SCOPE,type DriveIntent,type DriveReceipt,type SourceEvent} from '../../src/application/drive';
import {productionDriveService} from '../../src/server/drive/runtime';
const bytes=Buffer.from('%PDF-1.7\nSYNTHETIC header-only, not a parsed PDF');
const binding={id:'b',accountId:'account',folderId:'folder'};
const input={id:'40000000-0000-4000-8000-000000000001',projectId:'40000000-0000-4000-8000-000000000002',paperId:'40000000-0000-4000-8000-000000000003',filename:'SYNTHETIC.pdf',size:bytes.length,edition:'Original',source:'SYNTHETIC',accessBasis:'synthetic fixture'};
function fixture(){let intent:DriveIntent|null=null,receipt:DriveReceipt|null=null,revision='r1',changed=false,missing=false,deny=false,dbFail=false,content:Uint8Array=bytes;const events:SourceEvent[]=[];
const repo:DriveRepository={async authorize(){if(deny)throw new DriveError('FORBIDDEN');},async binding(){return binding;},async findIntent(){return intent;},async begin(i,b,file){return intent={...i,binding:b,fileId:file,expiresAt:Date.now()+10000,cancelled:false};},async receipt(){return receipt;},async finalize(i,v){if(dbFail)throw new DriveError('RETRYABLE');return receipt??={id:'receipt',intentId:i.id,projectId:i.projectId,paperId:i.paperId,provider:'google_drive',fileId:i.fileId,...v,state:'stored_unparsed'};},async event(_,s){events.push(s);},async cancel(i){i.cancelled=true;}};
const adapter:DriveAdapter={async quota(){return {available:100000000,maxUpload:100000000};},async allocate(){return 'file';},async start(){return 'https://www.googleapis.com/upload/drive/v3/files?upload_id=SYNTHETIC';},async metadata(i){if(missing)throw new DriveError('UNAVAILABLE');return {id:i.fileId,headRevisionId:revision,size:i.size,mimeType:'application/pdf',trashed:false,privateOwned:true,parents:['folder'],intentId:i.id};},async stream(){return new ReadableStream({start(c){c.enqueue(content.subarray(0,4));c.enqueue(content.subarray(4));if(changed)revision='r2';c.close();}});}};
let session:string|undefined;const vault:SessionVault={async once(_,__,fn){return session??=await fn();}};
return {service:new DriveService(repo,adapter,vault),adapter,events,get receipt(){return receipt;},set changed(v:boolean){changed=v;},set missing(v:boolean){missing=v;},set deny(v:boolean){deny=v;},set dbFail(v:boolean){dbFail=v;},set content(v:Uint8Array){content=v;}};}
test('Drive receipt streams exact hash without parsing or confirming',async()=>{const f=fixture();await f.service.begin(input);const r=await f.service.complete(input.id);assert.equal(r.sha256,createHash('sha256').update(bytes).digest('hex'));assert.equal(r.state,'stored_unparsed');assert.equal('pageCount' in r,false);assert.equal((await f.service.complete(input.id)).id,r.id);});
test('revision change during streaming refuses mixed/newer receipt',async()=>{const f=fixture();await f.service.begin(input);f.changed=true;await assert.rejects(f.service.complete(input.id),/REPLACED/);assert.equal(f.receipt,null);assert.deepEqual(f.events,['replaced']);});
test('missing object and database failure remain retryable',async()=>{const f=fixture();await f.service.begin(input);f.missing=true;await assert.rejects(f.service.complete(input.id),/UNAVAILABLE/);f.missing=false;f.dbFail=true;await assert.rejects(f.service.complete(input.id),/RETRYABLE/);f.dbFail=false;assert.equal((await f.service.complete(input.id)).state,'stored_unparsed');});
test('wrong size/header cannot produce receipt',async()=>{for(const content of [Buffer.alloc(bytes.length,0),Buffer.alloc(bytes.length+1,0)]){const f=fixture();await f.service.begin(input);f.content=content;await assert.rejects(f.service.complete(input.id),/INVALID_PDF|OVERSIZE/);assert.equal(f.receipt,null);}});
test('owner checks, cancellation and immutable intent input enforced',async()=>{const f=fixture();await f.service.begin(input);await assert.rejects(f.service.begin({...input,edition:'different'}),/CONFLICT/);f.deny=true;await assert.rejects(f.service.complete(input.id),/FORBIDDEN/);f.deny=false;await f.service.cancel(input.id);await assert.rejects(f.service.complete(input.id),/CANCELLED/);});
test('private download checks exact source but transport remains closed',async()=>{const f=fixture();await f.service.begin(input);await f.service.complete(input.id);await assert.rejects(f.service.download(input.id),/DOWNLOAD_UNPROVEN/);f.changed=true;await assert.rejects(f.service.download(input.id),/REPLACED/);assert.equal(f.receipt?.revisionId,'r1');});
test('unknown/insufficient quota refuses before upload',async()=>{const f=fixture();f.adapter.quota=async()=>({available:0,maxUpload:100000000});await assert.rejects(f.service.begin(input),/QUOTA/);});
test('runtime and dangerous session URLs fail closed',()=>{assert.throws(productionDriveService,/UNCONFIGURED/);for(const url of ['https://evil.test/upload','http://www.googleapis.com/upload/drive/v3/files?upload_id=x','https://www.googleapis.com/else?upload_id=x'])assert.throws(()=>assertSessionURL(url),/CONFLICT/);});
test('Google adapter detects wrong account and revoked/expired grants without token leakage',async()=>{for(const mode of ['wrong','expired','revoked']){const http=(async()=>mode==='revoked'?new Response('',{status:401}):Response.json({user:{permissionId:'wrong'}})) as typeof fetch;const a=new GoogleDriveAdapter({async access(){if(mode==='expired')throw Error('secret refresh token');return {accessToken:'secret access token',scopes:[DRIVE_SCOPE]};}},http);await assert.rejects(a.quota(binding),mode==='wrong'?/WRONG_ACCOUNT/:/RECONNECT/);}});
test('Google adapter uses only drive.file and new-file resumable request',async()=>{const calls:{url:string;init?:RequestInit}[]=[];const a=new GoogleDriveAdapter({async access(){return {accessToken:'SYNTHETIC token',scopes:[DRIVE_SCOPE]};}},(async(url,init)=>{calls.push({url:String(url),init});return String(url).includes('/about?')?Response.json({user:{permissionId:'account'},storageQuota:{limit:'100000000',usage:'0'},maxUploadSize:'100000000'}):String(url).includes('/files/folder?')?Response.json({id:'folder',mimeType:'application/vnd.google-apps.folder',ownedByMe:true,shared:false,appProperties:{kgFolder:'originals'}}):new Response('',{headers:{location:'https://www.googleapis.com/upload/drive/v3/files?upload_id=SYNTHETIC'}});}) as typeof fetch);const i={...input,binding,fileId:'new-file',expiresAt:Date.now()+1000,cancelled:false};await a.start(i);const call=calls.at(-1)!;assert.equal(call.init?.method,'POST');assert.equal(new URL(call.url).searchParams.get('keepRevisionForever'),'true');assert.equal(JSON.parse(String(call.init?.body)).id,'new-file');assert.deepEqual(JSON.parse(String(call.init?.body)).parents,['folder']);assert.equal(call.init?.redirect,'error');});

test('retired Storage endpoints are permanently gone and Drive body is not consumed',async()=>{const old=await import('../../src/app/api/pdf/route');const view=await import('../../src/app/projects/[projectId]/papers/[paperId]/pdf/[assetId]/route');const drive=await import('../../src/app/api/drive/route');assert.equal((await old.POST()).status,410);assert.equal((await view.GET()).status,410);assert.equal((await drive.POST(new Request('https://synthetic.example/api/drive',{method:'POST'}))).status,503);});
test('OAuth preparation binds state to app user with PKCE and only drive.file',async()=>{const {authorizationRequest}=await import('../../src/server/drive/oauth');let stored:Record<string,unknown>|undefined;const raw=await authorizationRequest({clientId:'SYNTHETIC',redirectUri:'https://synthetic.example/api/oauth/callback'},'synthetic-user',null,{async put(r){stored=r;},async consume(){return null;}});const url=new URL(raw);assert.equal(url.searchParams.get('scope'),DRIVE_SCOPE);assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(stored?.userId,'synthetic-user');assert.notEqual(stored?.stateHash,url.searchParams.get('state'));assert.equal(raw.includes(String(stored?.verifier)),false);});

test('streamed PDF header rejects high-bit aliases, malformed and truncated lines',async()=>{for(const content of [Buffer.concat([Buffer.from('a5d0c4c6adb1aeb7','hex'),Buffer.from('\n')]),Buffer.from('%PDF-1.7'),Buffer.from('%PDF-1.70\n'),Buffer.from('%PDF-x.y\n')]){const f=fixture();f.content=content;await f.service.begin({...input,size:content.length});await assert.rejects(f.service.complete(input.id),/INVALID_PDF/);assert.equal(f.receipt,null);}});
test('valid header split over stream chunks stays exact and is accepted',async()=>{const f=fixture();await f.service.begin(input);assert.equal((await f.service.complete(input.id)).sha256,createHash('sha256').update(bytes).digest('hex'));});
