import test from 'node:test';import assert from 'node:assert/strict';
import {DriveOAuth,encryptedSessions} from '../../src/server/drive/oauth-service';
import type {SecretVault,VaultTransaction} from '../../src/server/drive/vault';
import {DRIVE_SCOPE,type DriveBinding} from '../../src/application/drive';
const project='22222222-2222-4222-8222-222222222222',user='11111111-1111-4111-8111-111111111111';
class MemoryVault implements SecretVault {rows=new Map<string,{value:unknown;expiry:number}>();private tail=Promise.resolve();async transaction<T>(key:string,fn:(tx:VaultTransaction)=>Promise<T>):Promise<T>{const previous=this.tail;let release!:()=>void;this.tail=new Promise<void>(r=>release=r);await previous;try{const r=this.rows.get(key);return await fn({value:r&&r.expiry>Date.now()?r.value:null,put:(value,expiry)=>{this.rows.set(key,{value,expiry});},remove:()=>{this.rows.delete(key);}});}finally{release();}}}
function fixture(){const vault=new MemoryVault();let binding:DriveBinding|null=null,account='SYNTHETIC-account',refresh=0,exchange=0;const http:typeof fetch=async(input,init)=>{const url=String(input);assert.equal(init?.redirect,'error');assert.equal(init?.cache,'no-store');if(url==='https://oauth2.googleapis.com/token'){const b=init?.body as URLSearchParams;assert.equal(b.get('client_secret'),'SYNTHETIC-secret');if(b.get('grant_type')==='refresh_token'){refresh++;return Response.json({access_token:'SYNTHETIC-refreshed',expires_in:3600});}exchange++;assert.ok(b.get('code_verifier'));return Response.json({access_token:'SYNTHETIC-access',refresh_token:'SYNTHETIC-refresh',expires_in:1,scope:DRIVE_SCOPE});}if(url.includes('/about?'))return Response.json({user:{permissionId:account}});if(url.includes('/files/SYNTHETIC-folder?'))return Response.json({id:'SYNTHETIC-folder',mimeType:'application/vnd.google-apps.folder',ownedByMe:true,shared:false,appProperties:{kgFolder:'originals'}});if(url.includes('/files?'))return Response.json({id:'SYNTHETIC-folder'});throw Error('unexpected request');};const oauth=new DriveOAuth({clientId:'SYNTHETIC-client',clientSecret:'SYNTHETIC-secret',redirectUri:'https://synthetic.example/api/drive/oauth/callback'},user,vault,{async project(){return binding;},async bind(id,p,a,f){assert.equal(p,project);binding={id,accountId:a,folderId:f};}},http);return {vault,oauth,get binding(){return binding;},set account(v:string){account=v;},get refresh(){return refresh;},get exchange(){return exchange;}};}
test('OAuth state/callback/binding/refresh/session compose and survive new service instances',async()=>{const f=fixture();const url=new URL(await f.oauth.start(project));assert.equal(url.searchParams.get('scope'),DRIVE_SCOPE);assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(await f.oauth.callback(url.searchParams.get('state')!,'SYNTHETIC-code'),project);assert.ok(f.binding);const grants=await Promise.all([f.oauth.access(f.binding!.id),f.oauth.access(f.binding!.id)]);assert.equal(f.refresh,1);assert.equal(grants[0].accessToken,'SYNTHETIC-refreshed');await assert.rejects(f.oauth.callback(url.searchParams.get('state')!,'SYNTHETIC-code'));assert.equal(f.exchange,1);let created=0;const create=async()=>{created++;return 'https://www.googleapis.com/upload/drive/v3/files?upload_id=SYNTHETIC';};const id='33333333-3333-4333-8333-333333333333';const sessions=await Promise.all([encryptedSessions(f.vault).once(id,Date.now()+10000,create),encryptedSessions(f.vault).once(id,Date.now()+10000,create)]);assert.equal(created,1);assert.equal(sessions[0],sessions[1]);});
test('wrong-account reconnect never replaces binding or token',async()=>{const f=fixture();let url=new URL(await f.oauth.start(project));await f.oauth.callback(url.searchParams.get('state')!,'SYNTHETIC-code');const old={...f.binding};url=new URL(await f.oauth.start(project));f.account='OTHER-SYNTHETIC-account';await assert.rejects(f.oauth.callback(url.searchParams.get('state')!,'SYNTHETIC-code'),/WRONG_ACCOUNT/);assert.deepEqual(f.binding,old);});
test('missing or expired state stops before token exchange',async()=>{const f=fixture();await assert.rejects(f.oauth.callback('a'.repeat(43),'SYNTHETIC-code'));const url=new URL(await f.oauth.start(project));for(const r of f.vault.rows.values())r.expiry=0;await assert.rejects(f.oauth.callback(url.searchParams.get('state')!,'SYNTHETIC-code'));assert.equal(f.exchange,0);});
test('concurrent first callbacks serialize project binding and do not overwrite the winner',async()=>{const f=fixture();const a=new URL(await f.oauth.start(project)),b=new URL(await f.oauth.start(project));const results=await Promise.allSettled([f.oauth.callback(a.searchParams.get('state')!,'SYNTHETIC-a'),f.oauth.callback(b.searchParams.get('state')!,'SYNTHETIC-b')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(f.exchange,1);assert.ok(f.binding);assert.ok(f.vault.rows.has('token:'+f.binding!.id));});
