import test from 'node:test';import assert from 'node:assert/strict';
import {DriveWorker,workerPreflight,type SQLPool} from '../../src/server/drive/worker';
import {createWorkerPool} from '../../src/server/drive/connection';
const id='11111111-1111-4111-8111-111111111111';
const safe={login:'kg_test_worker',session_login:'kg_test_worker',worker_usage:true,extra_membership:false,delegable_role:false,elevated:false,owner_member:false,app_member:false,excessive_schema:false,table_access:false,extra_definer:false};
function fake(guard=safe,fail=false){const calls:{sql:string;args?:unknown[]}[]=[];let destroyed=false,connected=0;const pool:SQLPool={async connect(){connected++;return {async query(sql,args){calls.push({sql,args});if(sql===workerPreflight)return {rows:[guard]};if(sql.includes('finish_drive')){if(fail)throw Error('private connection string must not leak');return {rows:[{result:id}]};}return {rows:[]};},release(d){destroyed=!!d;}};}};return {pool,calls,get destroyed(){return destroyed;},get connected(){return connected;}};}
test('worker revalidates JWT before connecting and parameterizes verified subject',async()=>{const f=fake();const worker=new DriveWorker(f.pool,async jwt=>{assert.equal(jwt,'SYNTHETIC JWT');return {id};},'kg_test_worker');assert.equal(await worker.finish('SYNTHETIC JWT',id,{revisionId:"synthetic ' revision",sha256:'a'.repeat(64),byteSize:9}),id);assert.ok(f.calls.some(c=>c.sql.includes('set_config')&&c.args?.[0]===id));const call=f.calls.find(c=>c.sql.startsWith('select kg_private.finish_drive'))!;assert.equal(call.sql.includes('synthetic'),false);assert.equal(call.args?.[1],"synthetic ' revision");assert.deepEqual(f.calls.slice(-2).map(c=>c.sql),['COMMIT','RESET request.jwt.claim.sub']);assert.equal(f.destroyed,false);});
test('invalid JWT and unsafe connection privileges refuse before function call',async()=>{const f=fake();await assert.rejects(new DriveWorker(f.pool,async()=>{throw Error('expired');},'kg_test_worker').finish('invalid',id,{revisionId:'r',sha256:'a'.repeat(64),byteSize:9}),/FORBIDDEN/);assert.equal(f.connected,0);for(const guard of [{...safe,extra_membership:true},{...safe,delegable_role:true},{...safe,elevated:true},{...safe,owner_member:true},{...safe,table_access:true},{...safe,extra_definer:true},{...safe,session_login:'postgres'}]){const g=fake(guard);await assert.rejects(new DriveWorker(g.pool,async()=>({id}),'kg_test_worker').finish('synthetic',id,{revisionId:'r',sha256:'a'.repeat(64),byteSize:9}),/UNCONFIGURED/);assert.equal(g.calls.some(c=>c.sql.startsWith('select kg_private.finish_drive')),false);assert.equal(g.destroyed,true);}});
test('worker rollback discards errored connection and sanitizes raw driver errors',async()=>{const f=fake(safe,true);await assert.rejects(new DriveWorker(f.pool,async()=>({id}),'kg_test_worker').finish('synthetic',id,{revisionId:'r',sha256:'a'.repeat(64),byteSize:9}),e=>e instanceof Error&&e.message==='RETRYABLE');assert.equal(f.calls.at(-1)?.sql,'ROLLBACK');assert.equal(f.destroyed,true);});
test('connection constructor refuses absent/admin credentials without opening a connection',()=>{assert.throws(()=>createWorkerPool({host:'synthetic.invalid',port:5432,database:'postgres',login:'postgres',password:'synthetic'}),/UNCONFIGURED/);assert.throws(()=>createWorkerPool({host:'synthetic.invalid',port:5432,database:'postgres',login:'worker',password:''}),/UNCONFIGURED/);});
