import test from 'node:test';import assert from 'node:assert/strict';import type {SupabaseClient} from '@supabase/supabase-js';
import {HandoffDAL} from '../../src/server/research-handoff';
import {POST} from '../../src/app/api/handoff/route';
const id='11111111-1111-4111-8111-111111111111';
test('handoff authorization runs before any private query or mutation',async()=>{const dal=new HandoffDAL({} as SupabaseClient,async()=>{throw Error('denied');});await assert.rejects(dal.overview(id),/denied/);await assert.rejects(dal.download(id,id),/denied/);await assert.rejects(dal.request(id,id,id,id,id),/denied/);await assert.rejects(dal.stage(id,id,'{}'),/denied/);await assert.rejects(dal.revise(id,id,id,0,{}),/denied/);});
test('export includes project and request filters, immutable snapshot/template and no network dispatch',async()=>{const filters:unknown[]=[];const snapshot={case_import:{expected_revision:3},sources:[{pdf_sha256:'synthetic'}]};const q={select(){return q;},eq(k:string,v:string){filters.push([k,v]);return q;},async maybeSingle(){return {data:{id,content_hash:'a'.repeat(64),snapshot},error:null};}};const dal=new HandoffDAL({from(){return q;}} as unknown as SupabaseClient,async()=>{});const p=await dal.download(id,id);assert.deepEqual(filters,[['project_id',id],['id',id]]);assert.deepEqual(p.result_template.case_import,snapshot.case_import);assert.equal(p.result_template.conclusion,'');assert.match(p.instructions,/No recursive exploration/);});
test('missing private request produces safe forbidden response',async()=>{const q={select(){return q;},eq(){return q;},async maybeSingle(){return {data:null,error:null};}};const dal=new HandoffDAL({from(){return q;}} as unknown as SupabaseClient,async()=>{});await assert.rejects(dal.download(id,id),/FORBIDDEN/);});
test('handoff route blocks cross-origin mutations and oversized bodies before authentication',async()=>{const foreign=await POST(new Request('https://example.invalid/api/handoff',{method:'POST',headers:{origin:'https://attacker.invalid'},body:'{}'}));assert.equal(foreign.status,403);const big=await POST(new Request('https://example.invalid/api/handoff',{method:'POST',headers:{origin:'https://example.invalid'},body:' '.repeat(393217)}));assert.equal(big.status,400);assert.equal(big.headers.get('cache-control'),'private, no-store');});
test('question overview retains historical answer and flags changed or withdrawn evidence',async()=>{const rows:Record<string,unknown[]>={research_questions:[{id,question:'Original'}],question_revisions:[{id,question_id:id,revision:2,data:{question:'Edited',status:'answered',evidence_versions:['current','old','withdrawn']}}],research_requests:[],research_results:[],research_cases:[{id:'case',current_version_id:'current'},{id:'case2',current_version_id:'withdrawn'}],research_case_versions:[{id:'current',payload:{evidence:{source_anchor_id:'anchor'}}},{id:'old',payload:{evidence:{source_anchor_id:'anchor'}}},{id:'withdrawn',payload:{evidence:{source_anchor_id:'withdrawn-anchor'}}}],scientific_evidence_reviews:[{case_version_id:'current',decision:'accepted',source_attestation_id:'attestation'},{case_version_id:'withdrawn',decision:'accepted',source_attestation_id:'withdrawn-attestation'}],source_attestations:[{id:'attestation',anchor_id:'anchor',decision:'attested'},{id:'withdrawn-attestation',anchor_id:'withdrawn-anchor',decision:'withdrawn'}],source_anchors:[]};const client={from(table:string){const q=Object.assign(Promise.resolve({data:rows[table],error:null}),{select(){return q;},eq(){return q;},order(){return q;},limit(){return q;},is(){return q;}});return q;}} as unknown as SupabaseClient;const overview=await new HandoffDAL(client,async()=>{}).overview(id);assert.equal(overview.questions[0].question,'Edited');assert.equal(overview.questions[0].data?.status,'answered');assert.deepEqual(overview.invalidEvidenceVersions,['old','withdrawn']);assert.equal(overview.history.length,1);});
