import test from 'node:test';import assert from 'node:assert/strict';import type {SupabaseClient} from '@supabase/supabase-js';
import {HandoffDAL} from '../../src/server/research-handoff';
import {POST} from '../../src/app/api/handoff/route';
const id='11111111-1111-4111-8111-111111111111';
test('handoff authorization runs before any private query or mutation',async()=>{const dal=new HandoffDAL({} as SupabaseClient,async()=>{throw Error('denied');});await assert.rejects(dal.overview(id),/denied/);await assert.rejects(dal.download(id,id),/denied/);await assert.rejects(dal.request(id,id,id,id,id),/denied/);await assert.rejects(dal.stage(id,id,'{}'),/denied/);await assert.rejects(dal.revise(id,id,id,0,{}),/denied/);});
test('export includes project and request filters, immutable snapshot/template and no network dispatch',async()=>{const filters:unknown[]=[];const snapshot={case_import:{expected_revision:3},sources:[{pdf_sha256:'synthetic'}]};const q={select(){return q;},eq(k:string,v:string){filters.push([k,v]);return q;},async maybeSingle(){return {data:{id,content_hash:'a'.repeat(64),snapshot},error:null};}};const dal=new HandoffDAL({from(){return q;}} as unknown as SupabaseClient,async()=>{});const p=await dal.download(id,id);assert.deepEqual(filters,[['project_id',id],['id',id]]);assert.deepEqual(p.result_template.case_import,snapshot.case_import);assert.equal(p.result_template.conclusion,'');assert.match(p.instructions,/No recursive exploration/);});
test('missing private request produces safe forbidden response',async()=>{const q={select(){return q;},eq(){return q;},async maybeSingle(){return {data:null,error:null};}};const dal=new HandoffDAL({from(){return q;}} as unknown as SupabaseClient,async()=>{});await assert.rejects(dal.download(id,id),/FORBIDDEN/);});
test('handoff route blocks cross-origin mutations and oversized bodies before authentication',async()=>{const foreign=await POST(new Request('https://example.invalid/api/handoff',{method:'POST',headers:{origin:'https://attacker.invalid'},body:'{}'}));assert.equal(foreign.status,403);const big=await POST(new Request('https://example.invalid/api/handoff',{method:'POST',headers:{origin:'https://example.invalid'},body:' '.repeat(393217)}));assert.equal(big.status,400);assert.equal(big.headers.get('cache-control'),'private, no-store');});
test('question overview retains historical answer and flags changed or withdrawn evidence',async()=>{const rows:Record<string,unknown[]>={research_questions:[{id,question:'Original'}],question_revisions:[{id,question_id:id,revision:2,data:{question:'Edited',status:'answered',evidence_versions:['current','old','withdrawn']}}],research_requests:[],research_results:[],research_cases:[{id:'case',current_version_id:'current',paper_id:'paper',archived_at:null},{id:'case2',current_version_id:'withdrawn',paper_id:'paper',archived_at:null}],research_case_versions:[{id:'current',payload:{evidence:{source_anchor_id:'anchor'}}},{id:'old',payload:{evidence:{source_anchor_id:'anchor'}}},{id:'withdrawn',payload:{evidence:{source_anchor_id:'withdrawn-anchor'}}}],scientific_evidence_reviews:[{id:'review-current',case_version_id:'current',decision:'accepted',source_attestation_id:'attestation'},{id:'review-withdrawn',case_version_id:'withdrawn',decision:'accepted',source_attestation_id:'withdrawn-attestation'}],source_attestations:[{id:'attestation',anchor_id:'anchor',decision:'attested'},{id:'withdrawn-attestation',anchor_id:'withdrawn-anchor',decision:'withdrawn'}],source_anchors:[{id:'anchor',supersedes_anchor_id:null},{id:'withdrawn-anchor',supersedes_anchor_id:null}],papers:[{id:'paper',archived_at:null}]};const client={from(table:string){const q=Object.assign(Promise.resolve({data:rows[table],count:rows[table].length,error:null}),{select(){return q;},eq(){return q;},order(){return q;},limit(){return q;},is(){return q;},range(){return q;}});return q;}} as unknown as SupabaseClient;const overview=await new HandoffDAL(client,async()=>{}).overview(id);assert.equal(overview.questions[0].question,'Edited');assert.equal(overview.questions[0].data?.status,'answered');assert.deepEqual(overview.invalidEvidenceVersions,['old','withdrawn']);assert.equal(overview.history.length,1);rows.papers=[{id:'paper',archived_at:'2026-10-02'}];assert.ok((await new HandoffDAL(client,async()=>{}).overview(id)).invalidEvidenceVersions.includes('current'));});

test('capped incomplete response fails closed rather than keeping an answered question current',async()=>{const client={from(){const q=Object.assign(Promise.resolve({data:[],count:2,error:null}),{select(){return q;},eq(){return q;},order(){return q;},range(){return q;}});return q;}} as unknown as SupabaseClient;await assert.rejects(new HandoffDAL(client,async()=>{}).overview(id),/UNAVAILABLE/);});
test('exact-count paging follows a one-row server cap and missing answer evidence is invalid',async()=>{const pages:Record<string,number[]>={};const rows:Record<string,unknown[]>={research_questions:[{id,question:'Q'}],question_revisions:[{id:'r1',question_id:id,revision:1,data:{question:'Q',status:'answered',evidence_versions:['omitted-version']}}],source_anchors:[{id:'a',supersedes_anchor_id:null},{id:'b',supersedes_anchor_id:'a'}]};const client={from(table:string){let offset=0;const q={select(){return q;},eq(){return q;},order(){return q;},range(n:number){offset=n;(pages[table]??=[]).push(n);return q;},then(resolve:(v:unknown)=>unknown){const all=rows[table]??[];return Promise.resolve({data:all.slice(offset,offset+1),count:all.length,error:null}).then(resolve);}};return q;}} as unknown as SupabaseClient;const result=await new HandoffDAL(client,async()=>{}).overview(id);assert.deepEqual(pages.source_anchors,[0,1]);assert.ok(result.invalidEvidenceVersions.includes('omitted-version'));});
