import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PDFDocument} from 'pdf-lib';
import {PdfService,inspectPDF,type PdfRepository,type PrivateStorage} from '../../src/server/pdf/service';
import {MAX_PDF_BYTES,PdfError,pdfLimit,type Intent,type Finalized,type UploadInput} from '../../src/application/pdf';
import {productionPDFService} from '../../src/server/pdf/runtime';
async function fixture(pages=2){const p=await PDFDocument.create();for(let n=0;n<pages;n++)p.addPage([200,200]).drawText('SYNTHETIC ONLY');return p.save();}
async function setup(){const bytes=await fixture();const project=randomUUID(),paper=randomUUID();let authorized=true,dbFail=false,clock=1000;const intents=new Map<string,Intent>(),objects=new Map<string,Uint8Array>(),assets=new Map<string,Finalized>();let signs=0;
 const repo:PdfRepository={async authorize(pid,pap){if(!authorized||pid!==project||pap!==paper)throw new PdfError('FORBIDDEN');},async intent(input){const old=intents.get(input.requestId);if(old){assert.deepEqual({...old,id:undefined,path:undefined,expiresAt:undefined,state:undefined,assetId:undefined},{...input,id:undefined,path:undefined,expiresAt:undefined,state:undefined,assetId:undefined});return old;}const i:Intent={...input,id:input.requestId,path:`${input.projectId}/${input.requestId}/original.pdf`,state:'awaiting',expiresAt:2000,assetId:null};intents.set(i.id,i);return i;},async getIntent(id){const i=intents.get(id);if(!i)throw new PdfError('FORBIDDEN');return i;},async mark(id,state){const i=intents.get(id)!;if(i.state==='finalized'||i.state==='cancelled')throw new PdfError('CONFLICT');i.state=state;},async finalize(i,v){if(dbFail)throw new PdfError('DATABASE');let result=assets.get(v.sha256);if(!result){result={assetId:i.id,documentId:randomUUID(),matchedKnownBytes:false};assets.set(v.sha256,result);}else result={...result,matchedKnownBytes:result.assetId!==i.id};i.state='finalized';i.assetId=result.assetId;return result;},async asset(){if(!assets.size)throw new PdfError('FORBIDDEN');return {path:[...objects.keys()][0]};}};
 const storage:PrivateStorage={async putOnce(path,b){const intent=[...intents.values()].find(i=>i.path===path);if(intent?.state!=='awaiting')throw new PdfError('FORBIDDEN');if(objects.has(path))return 'exists';objects.set(path,b.slice());return 'created';},async readBounded(path,max){const b=objects.get(path);if(!b)throw new PdfError('STORAGE');if(b.length>max)throw new PdfError('OVERSIZE');return b;},async sign(_path,seconds){assert.equal(seconds,60);signs++;return 'https://synthetic.invalid/private?expires=60';}};
 const service=new PdfService(repo,storage,MAX_PDF_BYTES,()=>clock);const input:UploadInput={projectId:project,paperId:paper,requestId:randomUUID(),filename:'synthetic.pdf',size:bytes.length,expectedHash:null,edition:'synthetic edition',source:'synthetic fixture',accessBasis:'generated for test'};
 return {service,input,bytes,intents,objects,assets,deny:()=>{authorized=false;},failDB:(v:boolean)=>{dbFail=v;},expire:()=>{clock=3000;},signs:()=>signs};}
test('PDF verifier derives original hash, bytes and physical page count; no page labels/anchors invented',async()=>{const b=await fixture();const v=await inspectPDF(b,MAX_PDF_BYTES);assert.equal(v.pageCount,2);assert.equal(v.byteSize,b.length);assert.match(v.sha256,/^[a-f0-9]{64}$/);assert.equal(v.mime,'application/pdf');});
test('non-PDF, malformed PDF, empty and oversized reject',async()=>{for(const b of [new Uint8Array(),Buffer.from('not a PDF'),Buffer.from('%PDF-1.7 this is broken and has no page tree')])await assert.rejects(inspectPDF(b,MAX_PDF_BYTES));await assert.rejects(inspectPDF(new Uint8Array(MAX_PDF_BYTES+1),MAX_PDF_BYTES),/OVERSIZE/);});
test('limit fails closed and production verifier is unconfigured',()=>{assert.equal(pdfLimit('1048576'),1048576);assert.throws(()=>pdfLimit('9000000'),/UNCONFIGURED/);assert.throws(productionPDFService,/UNCONFIGURED/);});
test('idempotent intent + repeated finalize return same asset and preserve bytes',async()=>{const h=await setup();const i=await h.service.begin(h.input);assert.equal((await h.service.begin(h.input)).id,i.id);const a=await h.service.upload(i.id,h.bytes);assert.equal((await h.service.finalize(i.id)).assetId,a.assetId);assert.equal(h.assets.size,1);assert.deepEqual(h.objects.get(i.path),h.bytes);});
test('uploaded bytes must match actual stored bytes even without client hash',async()=>{const h=await setup();const i=await h.service.begin(h.input);const changed=h.bytes.slice();changed[changed.length-2]^=1;h.objects.set(i.path,changed);await assert.rejects(h.service.upload(i.id,h.bytes),/MISMATCH|INVALID_PDF/);assert.equal(h.assets.size,0);assert.deepEqual(h.objects.get(i.path),changed);});
test('client hash mismatch retains failed object without finalizing',async()=>{const h=await setup();const i=await h.service.begin({...h.input,expectedHash:'0'.repeat(64)});await assert.rejects(h.service.upload(i.id,h.bytes),/MISMATCH/);assert.equal(h.intents.get(i.id)?.state,'failed');assert.equal(h.objects.size,1);assert.equal(h.assets.size,0);});
test('wrong byte count rejects before storage',async()=>{const h=await setup();const i=await h.service.begin(h.input);await assert.rejects(h.service.upload(i.id,h.bytes.slice(1)),/MISMATCH/);assert.equal(h.objects.size,0);});
test('expired intent cannot upload or finalize',async()=>{const h=await setup();const i=await h.service.begin(h.input);h.expire();await assert.rejects(h.service.upload(i.id,h.bytes),/EXPIRED/);await assert.rejects(h.service.finalize(i.id),/EXPIRED/);});
test('cross-project paths and revoked owner access fail',async()=>{const h=await setup();const i=await h.service.begin(h.input);i.path=`${randomUUID()}/${i.id}/original.pdf`;await assert.rejects(h.service.upload(i.id,h.bytes),/FORBIDDEN/);h.deny();await assert.rejects(h.service.begin(h.input),/FORBIDDEN/);});
test('upload success plus DB failure retains object, retry finalizes once',async()=>{const h=await setup();const i=await h.service.begin(h.input);h.failDB(true);await assert.rejects(h.service.upload(i.id,h.bytes),/DATABASE/);assert.equal(h.objects.size,1);assert.equal(h.assets.size,0);h.failDB(false);await h.service.finalize(i.id);assert.equal(h.assets.size,1);});
test('simultaneous same-byte attempts share asset but retain original attempts',async()=>{const h=await setup();const a=await h.service.begin(h.input),b=await h.service.begin({...h.input,requestId:randomUUID()});const results=await Promise.all([h.service.upload(a.id,h.bytes),h.service.upload(b.id,h.bytes)]);assert.equal(results[0].assetId,results[1].assetId);assert.equal(h.objects.size,2);assert.equal(h.assets.size,1);});
test('cancel preserves object and blocks finalization',async()=>{const h=await setup();const i=await h.service.begin(h.input);h.objects.set(i.path,h.bytes);await h.service.cancel(i.id);await assert.rejects(h.service.finalize(i.id),/CANCELLED/);assert.equal(h.objects.size,1);});
test('view reauthorizes each request and issues only 60-second URL',async()=>{const h=await setup();const i=await h.service.begin(h.input);await h.service.upload(i.id,h.bytes);const view=await h.service.view(h.input.projectId,h.input.paperId,i.id);assert.equal(view.expiresAt,61000);h.deny();await assert.rejects(h.service.view(h.input.projectId,h.input.paperId,i.id),/FORBIDDEN/);assert.equal(h.signs(),1);});

test('failed retained-object retry reads existing bytes without a forbidden INSERT',async()=>{const h=await setup();const i=await h.service.begin(h.input);h.objects.set(i.path,h.bytes);i.state='failed';const result=await h.service.upload(i.id,h.bytes);assert.equal(result.assetId,i.id);assert.equal(h.objects.size,1);});
