import type {ResearchQuestion,AcquisitionTask} from '../../../../application/literature';
import {literatureDAL} from '../../../../server/literature/dal';
import {AcquisitionEditor} from '../../../../components/literature';
import Link from 'next/link';
import {researchDAL} from '../../../../server/dal';
import {pdfQueue} from '../../../../server/pdf/queries';
import {driveAvailable} from '../../../../server/drive/runtime';
import {DriveUpload} from '../../../../components/drive-upload';
import {AccessState,Header} from '../../../../components/access';

export const dynamic='force-dynamic';
function safeURL(value:string|null){try{const u=new URL(value??'');return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
export default async function Queue({params}:{params:Promise<{projectId:string}>}){let project,papers,projectId;let planning:{questions:ResearchQuestion[];tasks:AcquisitionTask[]};try{({projectId}=await params);project=await (await researchDAL()).project(projectId);papers=await pdfQueue(projectId);planning=await (await literatureDAL()).overview(projectId);papers.sort((a,b)=>Math.min(4,...planning.tasks.filter(t=>t.paper_id===a.id).map(t=>t.priority))-Math.min(4,...planning.tasks.filter(t=>t.paper_id===b.id).map(t=>t.priority)));}catch(error){return <main><Header/><AccessState error={error}/></main>;}return <main><Header/><Link href={`/projects/${projectId}`}>← {project.name}</Link><h1>PDF が必要な論文</h1><p><Link href={`/projects/${projectId}/literature`}>文献検索・Research Question</Link></p><p>本文 PDF が未登録の論文です。論文情報と PDF の版は別々に保管します。</p>{!papers.length&&<p>現在、PDF 待ちはありません。</p>}{papers.map(p=><article className="panel" key={p.id}><h2><Link href={`/projects/${projectId}/papers/${p.id}`}>{p.title}</Link></h2><dl className="metadata"><dt>著者 / 年</dt><dd>{p.authors||'著者未登録'} / {p.year??'年不明'}</dd><dt>DOI</dt><dd>{p.doi??'未登録'}</dd><dt>取得元</dt><dd>{safeURL(p.canonical_url)?<a href={safeURL(p.canonical_url)!} rel="noreferrer">論文の取得元</a>:'未登録'}</dd><dt>優先度 / 調査理由</dt><dd>{planning.tasks.filter(t=>t.paper_id===p.id).map(t=>`${t.priority} / ${t.reason}`).join(' · ')||'未設定'}</dd><dt>Research Question</dt><dd>{planning.tasks.filter(t=>t.paper_id===p.id).map(t=>planning.questions.find(q=>q.id===t.question_id)?.question??'未指定').join(' / ')||'未指定'}</dd></dl>{planning.tasks.filter(t=>t.paper_id===p.id).map(t=><AcquisitionEditor key={`${t.id}:${t.revision}`} project={projectId} paper={p.id} questions={planning.questions} task={t}/>)}<details><summary>別の問いに取得計画を追加</summary><AcquisitionEditor project={projectId} paper={p.id} questions={planning.questions}/></details><DriveUpload projectId={projectId} paperId={p.id} enabled={driveAvailable&&!project.archived_at}/></article>)}</main>;}
