# .github/workflows/triggered-by-slack.yml
name: Slack-triggered workflow

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from Slack!"

